// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/fcntl.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/sys/file.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package file

const (
	XF_GETLK64               = 5
	XF_SETLK64               = 6
	XF_SETLKW64              = 7
	XLOCK_EX                 = 2
	XLOCK_NB                 = 4
	XLOCK_SH                 = 1
	XLOCK_UN                 = 8
	XL_INCR                  = 1
	XL_SET                   = 0
	XL_XTND                  = 2
	XSEEK_CUR                = 1
	XSEEK_END                = 2
	XSEEK_SET                = 0
	XS_IFBLK                 = 0
	XS_IFCHR                 = 0
	XS_IFDIR                 = 0
	XS_IFIFO                 = 0
	XS_IFLNK                 = 0
	XS_IFMT                  = 0
	XS_IFREG                 = 0
	XS_IFSOCK                = 0
	XS_IRGRP                 = 32
	XS_IROTH                 = 4
	XS_IRUSR                 = 0
	XS_IRWXG                 = 56
	XS_IRWXO                 = 7
	XS_IRWXU                 = 448
	XS_ISGID                 = 0
	XS_ISUID                 = 0
	XS_ISVTX                 = 0
	XS_IWGRP                 = 16
	XS_IWOTH                 = 2
	XS_IWUSR                 = 0
	XS_IXGRP                 = 8
	XS_IXOTH                 = 1
	XS_IXUSR                 = 0
	X_BITS_TYPESIZES_H       = 1
	X_BITS_TYPES_H           = 1
	X_FCNTL_H                = 1
	X_SYS_FILE_H             = 1
	X__CLOCKID_T_TYPE        = 0
	X__DADDR_T_TYPE          = 0
	X__FD_SETSIZE            = 1024
	X__INO_T_MATCHES_INO64_T = 1
	X__KEY_T_TYPE            = 0
	X__OFF_T_MATCHES_OFF64_T = 1
	X__O_LARGEFILE           = 0
	X__PID_T_TYPE            = 0
	X__S32_TYPE              = 0
	X__SLONG32_TYPE          = 0
	Xcreat                   = 0
	Xopen                    = 0
)
