// Code generated by running "go generate". DO NOT EDIT.

	// +build ignore
	
	// BEGIN OF FILE /usr/include/i386/_types.h 

typedef char __int8_t ;
typedef unsigned char __uint8_t ;
typedef short __int16_t ;
typedef unsigned short __uint16_t ;
typedef int __int32_t ;
typedef unsigned int __uint32_t ;
typedef long long __int64_t ;
typedef unsigned long long __uint64_t ;
typedef long __darwin_intptr_t ;
typedef unsigned int __darwin_natural_t ;
typedef int __darwin_ct_rune_t ;
typedef union {char __mbstate8 [128 ];long long _mbstateL ;}__mbstate_t ;
typedef __mbstate_t __darwin_mbstate_t ;
typedef long int __darwin_ptrdiff_t ;
typedef long unsigned int __darwin_size_t ;
typedef void *__darwin_va_list ;
typedef int __darwin_wchar_t ;
typedef __darwin_wchar_t __darwin_rune_t ;
typedef int __darwin_wint_t ;
typedef unsigned long __darwin_clock_t ;
typedef __uint32_t __darwin_socklen_t ;
typedef long __darwin_ssize_t ;
typedef long __darwin_time_t ;
// BEGIN OF FILE /usr/include/sys/_types.h 

typedef __int64_t __darwin_blkcnt_t ;
typedef __int32_t __darwin_blksize_t ;
typedef __int32_t __darwin_dev_t ;
typedef unsigned int __darwin_fsblkcnt_t ;
typedef unsigned int __darwin_fsfilcnt_t ;
typedef __uint32_t __darwin_gid_t ;
typedef __uint32_t __darwin_id_t ;
typedef __uint64_t __darwin_ino64_t ;
typedef __darwin_ino64_t __darwin_ino_t ;
typedef __darwin_natural_t __darwin_mach_port_name_t ;
typedef __darwin_mach_port_name_t __darwin_mach_port_t ;
typedef __uint16_t __darwin_mode_t ;
typedef __int64_t __darwin_off_t ;
typedef __int32_t __darwin_pid_t ;
typedef __uint32_t __darwin_sigset_t ;
typedef __int32_t __darwin_suseconds_t ;
typedef __uint32_t __darwin_uid_t ;
typedef __uint32_t __darwin_useconds_t ;
typedef unsigned char __darwin_uuid_t [16 ];
typedef char __darwin_uuid_string_t [37 ];
// BEGIN OF FILE /usr/include/ctype.h 

int isalnum (int );
int isalpha (int );
int isblank (int );
int iscntrl (int );
int isdigit (int );
int isgraph (int );
int islower (int );
int isprint (int );
int ispunct (int );
int isspace (int );
int isupper (int );
int isxdigit (int );
int tolower (int );
int toupper (int );
int isascii (int );
int toascii (int );
// BEGIN OF FILE /usr/include/i386/_types.h 

#define _BSD_I386__TYPES_H_ 
// BEGIN OF FILE /usr/include/ctype.h 

#define _CTYPE_G (2048l)
#define _CTYPE_SW2 (2147483648l)
// BEGIN OF FILE /usr/include/sys/_types.h 

#define __offsetof(type, field) ( ( size_t ) ( & ( ( type * ) 0 ) -> field ) )
// BEGIN OF FILE /usr/include/ctype.h 

#define _CTYPE_U (32768l)
#define _CTYPE_S (16384l)
#define _CTYPE_I (524288l)
#define _CTYPE_X (65536l)
#define _CTYPE_H_ 
#define _CTYPE_R (262144l)
#define _CTYPE_SW1 (1073741824l)
#define _CTYPE_L (4096l)
#define _CTYPE_SW0 (536870912l)
// BEGIN OF FILE /usr/include/sys/_types.h 

#define _SYS__TYPES_H_ 
// BEGIN OF FILE /usr/include/ctype.h 

#define _CTYPE_Q (2097152l)
#define __DARWIN_CTYPE_inline __header_inline
#define _CTYPE_B (131072l)
#define _CTYPE_SWM (3758096384l)
#define _CTYPE_D (1024l)
#define _CTYPE_T (1048576l)
#define _CTYPE_A (256l)
// BEGIN OF FILE /usr/include/sys/_types.h 

#define __DARWIN_NULL ( ( void * ) 0 )
// BEGIN OF FILE /usr/include/ctype.h 

#define _CTYPE_SW3 (3221225472l)
#define _CTYPE_P (8192l)
#define _CTYPE_SWS (30)
#define _CTYPE_C (512l)
#define __DARWIN_CTYPE_TOP_inline __header_inline
