// Code generated by running "go generate". DO NOT EDIT.

package libc

const (
	Dlfcn_RTLD_BINDING_MASK = 3
	Dlfcn_RTLD_DEEPBIND     = 8
	Dlfcn_RTLD_GLOBAL       = 256
	Dlfcn_RTLD_LAZY         = 1
	Dlfcn_RTLD_LOCAL        = 0
	Dlfcn_RTLD_NODELETE     = 4096
	Dlfcn_RTLD_NOLOAD       = 4
	Dlfcn_RTLD_NOW          = 2
	Dlfcn__DLFCN_H          = 1
)
