// Code generated by running "go generate". DO NOT EDIT.

	// +build ignore

	// BEGIN OF FILE /usr/include/x86_64-linux-gnu/bits/errno.h 

extern int *__errno_location(void);
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENAVAIL (119)
#define ELIBBAD (80)
#define ENOPROTOOPT (92)
#define ESTALE (116)
#define EILSEQ (84)
#define EREMCHG (78)
#define EREMOTEIO (121)
#define EMEDIUMTYPE (124)
#define ECONNREFUSED (111)
#define ENOTSOCK (88)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EDOM (33)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EIDRM (43)
#define ECHRNG (44)
#define ELOOP (40)
#define ENOANO (55)
#define EUSERS (87)
#define EOVERFLOW (75)
#define EKEYREVOKED (128)
#define ENOTUNIQ (76)
#define EBADE (52)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EINVAL (22)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EHWPOISON (133)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENOTDIR (20)
#define EROFS (30)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ECONNABORTED (103)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENXIO (6)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ESHUTDOWN (108)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EPERM (1)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ELNRNG (48)
#define ENOTCONN (107)
#define EL2HLT (51)
#define ENOMSG (42)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENOTBLK (15)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EADV (68)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EBADF (9)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EOPNOTSUPP (95)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EEXIST (17)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENOMEDIUM (123)
#define ENOPKG (65)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ESPIPE (29)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ERESTART (85)
#define ENETRESET (102)
#define ELIBEXEC (83)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENODEV (19)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EXFULL (54)
#define EPROTOTYPE (91)
#define ENOBUFS (105)
#define EALREADY (114)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define _ASM_GENERIC_ERRNO_BASE_H
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EDEADLK (35)
#define ENAMETOOLONG (36)
#define EBADRQC (56)
#define EMSGSIZE (90)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENFILE (23)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EPROTO (71)
#define EBADFD (77)
#define EHOSTDOWN (112)
#define ENOCSI (50)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EFAULT (14)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EKEYEXPIRED (127)
#define ENOSR (63)
#define EDOTDOT (73)
#define ECANCELED (125)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENOMEM (12)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENOLCK (37)
#define EUCLEAN (117)
#define ECONNRESET (104)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EISDIR (21)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EREMOTE (66)
#define EDQUOT (122)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ECHILD (10)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EMULTIHOP (72)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define E2BIG (7)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EL3RST (47)
#define EISCONN (106)
#define EDEADLOCK EDEADLK
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EXDEV (18)
#define EPIPE (32)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ETOOMANYREFS (109)
#define EBADR (53)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ETXTBSY (26)
#define ENOTTY (25)
#define ENOSPC (28)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EOWNERDEAD (130)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENOEXEC (8)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EBFONT (59)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EIO (5)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENOKEY (126)
#define ENONET (64)
#define ENOTEMPTY (39)
#define ENOTRECOVERABLE (131)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EMLINK (31)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EHOSTUNREACH (113)
#define ELIBACC (79)
#define EWOULDBLOCK EAGAIN
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EACCES (13)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EBADSLT (57)
#define EAFNOSUPPORT (97)
#define ERFKILL (132)
#define ENOLINK (67)
#define EBADMSG (74)
#define ELIBMAX (82)
// BEGIN OF FILE /usr/include/x86_64-linux-gnu/bits/errno.h 

#define ENOTSUP EOPNOTSUPP
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ESRCH (3)
#define EAGAIN (11)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EADDRNOTAVAIL (99)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EFBIG (27)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EKEYREJECTED (129)
#define _ASM_GENERIC_ERRNO_H
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define EMFILE (24)
#define EBUSY (16)
#define EINTR (4)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ESOCKTNOSUPPORT (94)
#define ELIBSCN (81)
#define EINPROGRESS (115)
#define ESRMNT (69)
#define EISNAM (120)
#define ENETDOWN (100)
#define ETIMEDOUT (110)
#define EUNATCH (49)
#define ENETUNREACH (101)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ENOENT (2)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define EL3HLT (46)
#define EDESTADDRREQ (89)
// BEGIN OF FILE /usr/include/asm-generic/errno-base.h 

#define ERANGE (34)
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENOTNAM (118)
#define EPROTONOSUPPORT (93)
#define EADDRINUSE (98)
#define ESTRPIPE (86)
#define ENOSTR (60)
#define ENOSYS (38)
#define ETIME (62)
#define EPFNOSUPPORT (96)
// BEGIN OF FILE /usr/include/x86_64-linux-gnu/bits/errno.h 

#define errno ( * __errno_location ( ) )
// BEGIN OF FILE /usr/include/asm-generic/errno.h 

#define ENODATA (61)
#define EL2NSYNC (45)
#define ECOMM (70)
