// Code generated by running "go generate". DO NOT EDIT.

// +build ignore

// ----------------------------------------------------------------------------
//      /usr/include/inttypes.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1997-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

typedef int __gwchar_t;
typedef struct {
	long int quot;
	long int rem;
} imaxdiv_t;
extern intmax_t imaxabs(intmax_t __n);
extern imaxdiv_t imaxdiv(intmax_t __numer, intmax_t __denom);
extern intmax_t strtoimax(const char *__nptr, char **__endptr, int __base);
extern uintmax_t strtoumax(const char *__nptr, char **__endptr, int __base);
extern intmax_t wcstoimax(const __gwchar_t * __nptr, __gwchar_t ** __endptr, int __base);
extern uintmax_t wcstoumax(const __gwchar_t * __nptr, __gwchar_t ** __endptr, int __base);

// /usr/include/inttypes.h 

#define SCNiFAST32 __PRIPTR_PREFIX "i"
#define SCNuFAST16 __PRIPTR_PREFIX "u"
#define SCNoFAST8 "hho"
#define PRIXFAST8 "X"
#define PRIuFAST16 __PRIPTR_PREFIX "u"
#define PRIuPTR __PRIPTR_PREFIX "u"
#define PRIX64 __PRI64_PREFIX "X"
#define PRIo16 "o"
#define PRIdPTR __PRIPTR_PREFIX "d"
#define SCNxLEAST8 "hhx"
#define PRIi64 __PRI64_PREFIX "i"
#define SCNxFAST16 __PRIPTR_PREFIX "x"
#define SCNoFAST32 __PRIPTR_PREFIX "o"
#define PRIXPTR __PRIPTR_PREFIX "X"
#define PRIdLEAST16 "d"
#define SCNuLEAST32 "u"
#define PRIdLEAST8 "d"
#define SCNiLEAST64 __PRI64_PREFIX "i"
#define SCNiFAST16 __PRIPTR_PREFIX "i"
#define SCNiMAX __PRI64_PREFIX "i"
#define PRIoFAST32 __PRIPTR_PREFIX "o"
#define PRIuLEAST64 __PRI64_PREFIX "u"
#define SCNd16 "hd"
#define SCNxLEAST64 __PRI64_PREFIX "x"
#define PRIXLEAST64 __PRI64_PREFIX "X"
#define SCNiLEAST8 "hhi"
#define PRIuLEAST8 "u"
#define SCNd32 "d"
#define SCNxFAST64 __PRI64_PREFIX "x"
#define SCNu16 "hu"
#define SCNu32 "u"
#define SCNiLEAST32 "i"
#define PRIoLEAST64 __PRI64_PREFIX "o"
#define PRIdLEAST64 __PRI64_PREFIX "d"
#define PRIXLEAST16 "X"
#define PRIiFAST32 __PRIPTR_PREFIX "i"
#define PRIx16 "x"
#define SCNi32 "i"
#define PRIuFAST32 __PRIPTR_PREFIX "u"
#define PRIXLEAST8 "X"
#define SCNdLEAST16 "hd"
#define PRIxMAX __PRI64_PREFIX "x"
#define SCNxFAST8 "hhx"
#define SCNuFAST64 __PRI64_PREFIX "u"
#define PRIX8 "X"
#define PRIdFAST64 __PRI64_PREFIX "d"
#define PRIXMAX __PRI64_PREFIX "X"
#define __PRI64_PREFIX "l"
#define PRIdMAX __PRI64_PREFIX "d"
#define PRIoLEAST32 "o"
#define SCNdLEAST32 "d"
#define SCNdLEAST64 __PRI64_PREFIX "d"
#define SCNoLEAST32 "o"
#define PRIiLEAST8 "i"
#define SCNo64 __PRI64_PREFIX "o"
#define SCNdMAX __PRI64_PREFIX "d"
#define PRIdFAST32 __PRIPTR_PREFIX "d"
#define SCNxFAST32 __PRIPTR_PREFIX "x"
#define PRIuFAST8 "u"
#define SCNoLEAST64 __PRI64_PREFIX "o"
#define SCNiFAST64 __PRI64_PREFIX "i"
#define __PRIPTR_PREFIX "l"
#define SCNuLEAST8 "hhu"
#define PRIxFAST8 "x"
#define SCNx32 "x"
#define SCNdFAST32 __PRIPTR_PREFIX "d"
#define PRIuLEAST32 "u"
#define PRIo64 __PRI64_PREFIX "o"
#define SCNu8 "hhu"
#define PRIi16 "i"
#define PRIoFAST16 __PRIPTR_PREFIX "o"
#define PRIxPTR __PRIPTR_PREFIX "x"
#define PRIo32 "o"
#define PRIoMAX __PRI64_PREFIX "o"
#define SCNi16 "hi"
#define SCNxLEAST32 "x"
#define SCNuMAX __PRI64_PREFIX "u"
#define PRIuMAX __PRI64_PREFIX "u"
#define SCNiPTR __PRIPTR_PREFIX "i"
#define PRIiFAST64 __PRI64_PREFIX "i"
#define PRIxLEAST32 "x"
#define PRIiMAX __PRI64_PREFIX "i"
#define PRIdLEAST32 "d"
#define PRIXFAST64 __PRI64_PREFIX "X"
#define PRIx8 "x"
#define SCNuFAST8 "hhu"
#define PRIu16 "u"
#define PRIu8 "u"
#define SCNx16 "hx"
#define PRIi8 "i"
#define PRIiLEAST16 "i"
#define SCNoMAX __PRI64_PREFIX "o"
#define PRIXLEAST32 "X"
#define PRIu32 "u"
#define SCNo16 "ho"
#define PRIxLEAST16 "x"
#define SCNoPTR __PRIPTR_PREFIX "o"
#define SCNxLEAST16 "hx"
#define SCNdFAST64 __PRI64_PREFIX "d"
#define SCNxPTR __PRIPTR_PREFIX "x"
#define PRId64 __PRI64_PREFIX "d"
#define SCNdPTR __PRIPTR_PREFIX "d"
#define SCNu64 __PRI64_PREFIX "u"
#define PRIiLEAST32 "i"
#define SCNoFAST16 __PRIPTR_PREFIX "o"
#define PRIo8 "o"
#define PRIXFAST32 __PRIPTR_PREFIX "X"
#define SCNo8 "hho"
#define SCNoLEAST16 "ho"
#define PRIu64 __PRI64_PREFIX "u"
#define SCNdFAST8 "hhd"
#define SCNd8 "hhd"
#define PRIxFAST16 __PRIPTR_PREFIX "x"
#define PRIoPTR __PRIPTR_PREFIX "o"
#define _INTTYPES_H (1)
#define SCNuLEAST16 "hu"
#define SCNuPTR __PRIPTR_PREFIX "u"
#define SCNi8 "hhi"
#define PRIxLEAST8 "x"
#define SCNiLEAST16 "hi"
#define PRId32 "d"
#define SCNd64 __PRI64_PREFIX "d"
#define PRIuFAST64 __PRI64_PREFIX "u"
#define PRIxFAST32 __PRIPTR_PREFIX "x"
#define SCNoLEAST8 "hho"
#define PRIoLEAST8 "o"
#define PRIoFAST8 "o"
#define SCNo32 "o"
#define PRIdFAST16 __PRIPTR_PREFIX "d"
#define PRIx64 __PRI64_PREFIX "x"
#define PRIX32 "X"
#define PRIxFAST64 __PRI64_PREFIX "x"
#define PRIdFAST8 "d"
#define PRIoLEAST16 "o"
#define PRIoFAST64 __PRI64_PREFIX "o"
#define PRId16 "d"
#define SCNxMAX __PRI64_PREFIX "x"
#define SCNi64 __PRI64_PREFIX "i"
#define PRIXFAST16 __PRIPTR_PREFIX "X"
#define PRIiFAST16 __PRIPTR_PREFIX "i"
#define PRIiPTR __PRIPTR_PREFIX "i"
#define SCNdFAST16 __PRIPTR_PREFIX "d"
#define SCNuLEAST64 __PRI64_PREFIX "u"
#define SCNx64 __PRI64_PREFIX "x"
#define PRIx32 "x"
#define SCNuFAST32 __PRIPTR_PREFIX "u"
#define PRIiFAST8 "i"
#define PRIX16 "X"
#define SCNiFAST8 "hhi"
#define PRIiLEAST64 __PRI64_PREFIX "i"
#define PRIi32 "i"
#define PRIxLEAST64 __PRI64_PREFIX "x"
#define SCNdLEAST8 "hhd"
#define SCNoFAST64 __PRI64_PREFIX "o"
#define PRIuLEAST16 "u"
#define PRId8 "d"
#define SCNx8 "hhx"
#define ____gwchar_t_defined (1)
