// Code generated by running "go generate". DO NOT EDIT.

	// +build ignore
	
	// BEGIN OF FILE m:\mingw\lib\gcc\x86_64-w64-mingw32\6.3.0\include\stdarg.h 

typedef __builtin_va_list __gnuc_va_list ;
// BEGIN OF FILE m:\mingw\lib\gcc\x86_64-w64-mingw32\6.3.0\include\stdarg.h 

#define va_copy(d, s) __builtin_va_copy ( d , s )
#define va_start(v, l) __builtin_va_start ( v , l )
#define __va_list__ 
#define _VA_LIST_ 
#define _VA_LIST_T_H 
#define va_end(v) __builtin_va_end ( v )
#define _STDARG_H 
#define va_arg(v, l) __builtin_va_arg ( v , l )
#define _ANSI_STDARG_H_ 
#define __GNUC_VA_LIST 
#define _VA_LIST 
#define __va_copy(d, s) __builtin_va_copy ( d , s )
