// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/i686-linux-gnu/6/include/stdarg.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

package libc

const (
	Xstdarg__BUILTIN_H_               = true
	Xstdarg__PREDEFINED_H_            = true
	Xstdarg__STDARG_H_                = true
	Xstdarg__STDC_PREDEF_H            = 1
	Xstdarg___ATOMIC_ACQUIRE          = 2
	Xstdarg___ATOMIC_ACQ_REL          = 4
	Xstdarg___ATOMIC_CONSUME          = 1
	Xstdarg___ATOMIC_HLE_ACQUIRE      = 65536
	Xstdarg___ATOMIC_HLE_RELEASE      = 131072
	Xstdarg___ATOMIC_RELAXED          = 0
	Xstdarg___ATOMIC_RELEASE          = 3
	Xstdarg___ATOMIC_SEQ_CST          = 5
	Xstdarg___BIGGEST_ALIGNMENT__     = 16
	Xstdarg___BYTE_ORDER__            = 1234
	Xstdarg___CHAR_BIT__              = 8
	Xstdarg___DBL_DECIMAL_DIG__       = 17
	Xstdarg___DBL_DIG__               = 15
	Xstdarg___DBL_HAS_DENORM__        = 1
	Xstdarg___DBL_HAS_INFINITY__      = 1
	Xstdarg___DBL_HAS_QUIET_NAN__     = 1
	Xstdarg___DBL_MANT_DIG__          = 53
	Xstdarg___DBL_MAX_10_EXP__        = 308
	Xstdarg___DBL_MAX_EXP__           = 1024
	Xstdarg___DBL_MIN_10_EXP__        = -307
	Xstdarg___DBL_MIN_EXP__           = -1021
	Xstdarg___DEC128_MANT_DIG__       = 34
	Xstdarg___DEC128_MAX_EXP__        = 6145
	Xstdarg___DEC128_MIN_EXP__        = -6142
	Xstdarg___DEC32_MANT_DIG__        = 7
	Xstdarg___DEC32_MAX_EXP__         = 97
	Xstdarg___DEC32_MIN_EXP__         = -94
	Xstdarg___DEC64_MANT_DIG__        = 16
	Xstdarg___DEC64_MAX_EXP__         = 385
	Xstdarg___DEC64_MIN_EXP__         = -382
	Xstdarg___DECIMAL_BID_FORMAT__    = 1
	Xstdarg___DECIMAL_DIG__           = 21
	Xstdarg___DEC_EVAL_METHOD__       = 2
	Xstdarg___FINITE_MATH_ONLY__      = 0
	Xstdarg___FLOAT_WORD_ORDER__      = 1234
	Xstdarg___FLT_DECIMAL_DIG__       = 9
	Xstdarg___FLT_DENORM_MIN__        = 1e-45
	Xstdarg___FLT_DIG__               = 6
	Xstdarg___FLT_EPSILON__           = 1.1920929e-07
	Xstdarg___FLT_EVAL_METHOD__       = 2
	Xstdarg___FLT_HAS_DENORM__        = 1
	Xstdarg___FLT_HAS_INFINITY__      = 1
	Xstdarg___FLT_HAS_QUIET_NAN__     = 1
	Xstdarg___FLT_MANT_DIG__          = 24
	Xstdarg___FLT_MAX_10_EXP__        = 38
	Xstdarg___FLT_MAX_EXP__           = 128
	Xstdarg___FLT_MAX__               = 3.4028235e+38
	Xstdarg___FLT_MIN_10_EXP__        = -37
	Xstdarg___FLT_MIN_EXP__           = -125
	Xstdarg___FLT_MIN__               = 1.1754944e-38
	Xstdarg___FLT_RADIX__             = 2
	Xstdarg___FUNCTION__              = 0
	Xstdarg___GXX_ABI_VERSION         = 1010
	Xstdarg___INT16_MAX__             = 32767
	Xstdarg___INT32_MAX__             = 2147483647
	Xstdarg___INT32_TYPE__            = 0
	Xstdarg___INT64_MAX__             = 9223372036854775807
	Xstdarg___INT8_MAX__              = 127
	Xstdarg___INTMAX_MAX__            = 9223372036854775807
	Xstdarg___INTPTR_MAX__            = 2147483647
	Xstdarg___INTPTR_TYPE__           = 0
	Xstdarg___INT_FAST16_MAX__        = 2147483647
	Xstdarg___INT_FAST16_TYPE__       = 0
	Xstdarg___INT_FAST32_MAX__        = 2147483647
	Xstdarg___INT_FAST32_TYPE__       = 0
	Xstdarg___INT_FAST64_MAX__        = 9223372036854775807
	Xstdarg___INT_FAST8_MAX__         = 127
	Xstdarg___INT_LEAST16_MAX__       = 32767
	Xstdarg___INT_LEAST32_MAX__       = 2147483647
	Xstdarg___INT_LEAST32_TYPE__      = 0
	Xstdarg___INT_LEAST64_MAX__       = 9223372036854775807
	Xstdarg___INT_LEAST8_MAX__        = 127
	Xstdarg___INT_MAX__               = 2147483647
	Xstdarg___LDBL_DENORM_MIN__       = 0
	Xstdarg___LDBL_DIG__              = 18
	Xstdarg___LDBL_EPSILON__          = 1.0842021724855044e-19
	Xstdarg___LDBL_HAS_DENORM__       = 1
	Xstdarg___LDBL_HAS_INFINITY__     = 1
	Xstdarg___LDBL_HAS_QUIET_NAN__    = 1
	Xstdarg___LDBL_MANT_DIG__         = 64
	Xstdarg___LDBL_MAX_10_EXP__       = 4932
	Xstdarg___LDBL_MAX_EXP__          = 16384
	Xstdarg___LDBL_MAX__              = 0
	Xstdarg___LDBL_MIN_10_EXP__       = -4931
	Xstdarg___LDBL_MIN_EXP__          = -16381
	Xstdarg___LDBL_MIN__              = 0
	Xstdarg___LONG_LONG_MAX__         = 9223372036854775807
	Xstdarg___LONG_MAX__              = 2147483647
	Xstdarg___NO_INLINE__             = 1
	Xstdarg___ORDER_BIG_ENDIAN__      = 4321
	Xstdarg___ORDER_LITTLE_ENDIAN__   = 1234
	Xstdarg___ORDER_PDP_ENDIAN__      = 3412
	Xstdarg___PRAGMA_REDEFINE_EXTNAME = 1
	Xstdarg___PTRDIFF_MAX__           = 2147483647
	Xstdarg___PTRDIFF_TYPE__          = 0
	Xstdarg___REGISTER_PREFIX__       = true
	Xstdarg___SCHAR_MAX__             = 127
	Xstdarg___SEG_FS                  = 1
	Xstdarg___SEG_GS                  = 1
	Xstdarg___SHRT_MAX__              = 32767
	Xstdarg___SIG_ATOMIC_MAX__        = 2147483647
	Xstdarg___SIG_ATOMIC_MIN__        = -2147483648
	Xstdarg___SIG_ATOMIC_TYPE__       = 0
	Xstdarg___SIZEOF_DOUBLE__         = 8
	Xstdarg___SIZEOF_FLOAT128__       = 16
	Xstdarg___SIZEOF_FLOAT80__        = 12
	Xstdarg___SIZEOF_FLOAT__          = 4
	Xstdarg___SIZEOF_INT__            = 4
	Xstdarg___SIZEOF_LONG_DOUBLE__    = 12
	Xstdarg___SIZEOF_LONG_LONG__      = 8
	Xstdarg___SIZEOF_LONG__           = 4
	Xstdarg___SIZEOF_POINTER__        = 4
	Xstdarg___SIZEOF_PTRDIFF_T__      = 4
	Xstdarg___SIZEOF_SHORT__          = 2
	Xstdarg___SIZEOF_SIZE_T__         = 4
	Xstdarg___SIZEOF_WCHAR_T__        = 4
	Xstdarg___SIZEOF_WINT_T__         = 4
	Xstdarg___SIZE_MAX__              = 4294967295
	Xstdarg___SSP_STRONG__            = 3
	Xstdarg___STDC_HOSTED__           = 1
	Xstdarg___STDC_IEC_559_COMPLEX__  = 1
	Xstdarg___STDC_IEC_559__          = 1
	Xstdarg___STDC_ISO_10646__        = 201505
	Xstdarg___STDC_NO_THREADS__       = 1
	Xstdarg___STDC_VERSION__          = 199901
	Xstdarg___STDC__                  = 1
	Xstdarg___STRICT_ANSI__           = 1
	Xstdarg___UINT16_MAX__            = 65535
	Xstdarg___UINT32_MAX__            = 4294967295
	Xstdarg___UINT64_MAX__            = 18446744073709551615
	Xstdarg___UINT8_MAX__             = 255
	Xstdarg___UINTMAX_MAX__           = 18446744073709551615
	Xstdarg___UINTPTR_MAX__           = 4294967295
	Xstdarg___UINT_FAST16_MAX__       = 4294967295
	Xstdarg___UINT_FAST32_MAX__       = 4294967295
	Xstdarg___UINT_FAST64_MAX__       = 18446744073709551615
	Xstdarg___UINT_FAST8_MAX__        = 255
	Xstdarg___UINT_LEAST16_MAX__      = 65535
	Xstdarg___UINT_LEAST32_MAX__      = 4294967295
	Xstdarg___UINT_LEAST64_MAX__      = 18446744073709551615
	Xstdarg___UINT_LEAST8_MAX__       = 255
	Xstdarg___USER_LABEL_PREFIX__     = true
	Xstdarg___VERSION__               = 39547
	Xstdarg___WCHAR_MAX__             = 2147483647
	Xstdarg___WCHAR_MIN__             = -2147483648
	Xstdarg___WINT_MAX__              = 4294967295
	Xstdarg___WINT_MIN__              = 0
	Xstdarg___arch__                  = 386
	Xstdarg___code_model_32__         = 1
	Xstdarg___complex__               = 0
	Xstdarg___const                   = 0
	Xstdarg___extension__             = true
	Xstdarg___i386                    = 1
	Xstdarg___i386__                  = 1
	Xstdarg___i686                    = 1
	Xstdarg___i686__                  = 1
	Xstdarg___inline                  = 0
	Xstdarg___linux                   = 1
	Xstdarg___linux__                 = 1
	Xstdarg___os__                    = 0
	Xstdarg___pentiumpro              = 1
	Xstdarg___pentiumpro__            = 1
	Xstdarg___restrict                = 0
	Xstdarg___unix                    = 1
	Xstdarg___unix__                  = 1
	Xstdarg___va_list__               = true
	Xstdarg___volatile                = 0
)
