// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/x86_64-linux-gnu/6/include/stdbool.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1998-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

package libc

const (
	Xstdbool__BUILTIN_H_                   = true
	Xstdbool__LP64                         = 1
	Xstdbool__PREDEFINED_H_                = true
	Xstdbool__STDBOOL_H_                   = true
	Xstdbool__STDC_PREDEF_H                = 1
	Xstdbool___ATOMIC_ACQUIRE              = 2
	Xstdbool___ATOMIC_ACQ_REL              = 4
	Xstdbool___ATOMIC_CONSUME              = 1
	Xstdbool___ATOMIC_HLE_ACQUIRE          = 65536
	Xstdbool___ATOMIC_HLE_RELEASE          = 131072
	Xstdbool___ATOMIC_RELAXED              = 0
	Xstdbool___ATOMIC_RELEASE              = 3
	Xstdbool___ATOMIC_SEQ_CST              = 5
	Xstdbool___BIGGEST_ALIGNMENT__         = 16
	Xstdbool___BYTE_ORDER__                = 1234
	Xstdbool___CHAR_BIT__                  = 8
	Xstdbool___DBL_DECIMAL_DIG__           = 17
	Xstdbool___DBL_DIG__                   = 15
	Xstdbool___DBL_HAS_DENORM__            = 1
	Xstdbool___DBL_HAS_INFINITY__          = 1
	Xstdbool___DBL_HAS_QUIET_NAN__         = 1
	Xstdbool___DBL_MANT_DIG__              = 53
	Xstdbool___DBL_MAX_10_EXP__            = 308
	Xstdbool___DBL_MAX_EXP__               = 1024
	Xstdbool___DBL_MIN_10_EXP__            = -307
	Xstdbool___DBL_MIN_EXP__               = -1021
	Xstdbool___DEC128_MANT_DIG__           = 34
	Xstdbool___DEC128_MAX_EXP__            = 6145
	Xstdbool___DEC128_MIN_EXP__            = -6142
	Xstdbool___DEC32_MANT_DIG__            = 7
	Xstdbool___DEC32_MAX_EXP__             = 97
	Xstdbool___DEC32_MIN_EXP__             = -94
	Xstdbool___DEC64_MANT_DIG__            = 16
	Xstdbool___DEC64_MAX_EXP__             = 385
	Xstdbool___DEC64_MIN_EXP__             = -382
	Xstdbool___DECIMAL_BID_FORMAT__        = 1
	Xstdbool___DECIMAL_DIG__               = 21
	Xstdbool___DEC_EVAL_METHOD__           = 2
	Xstdbool___FINITE_MATH_ONLY__          = 0
	Xstdbool___FLOAT_WORD_ORDER__          = 1234
	Xstdbool___FLT_DECIMAL_DIG__           = 9
	Xstdbool___FLT_DENORM_MIN__            = 1e-45
	Xstdbool___FLT_DIG__                   = 6
	Xstdbool___FLT_EPSILON__               = 1.1920929e-07
	Xstdbool___FLT_EVAL_METHOD__           = 0
	Xstdbool___FLT_HAS_DENORM__            = 1
	Xstdbool___FLT_HAS_INFINITY__          = 1
	Xstdbool___FLT_HAS_QUIET_NAN__         = 1
	Xstdbool___FLT_MANT_DIG__              = 24
	Xstdbool___FLT_MAX_10_EXP__            = 38
	Xstdbool___FLT_MAX_EXP__               = 128
	Xstdbool___FLT_MAX__                   = 3.4028235e+38
	Xstdbool___FLT_MIN_10_EXP__            = -37
	Xstdbool___FLT_MIN_EXP__               = -125
	Xstdbool___FLT_MIN__                   = 1.1754944e-38
	Xstdbool___FLT_RADIX__                 = 2
	Xstdbool___FUNCTION__                  = 0
	Xstdbool___FXSR__                      = 1
	Xstdbool___GXX_ABI_VERSION             = 1010
	Xstdbool___INT16_MAX__                 = 32767
	Xstdbool___INT32_MAX__                 = 2147483647
	Xstdbool___INT32_TYPE__                = 0
	Xstdbool___INT64_MAX__                 = 9223372036854775807
	Xstdbool___INT8_MAX__                  = 127
	Xstdbool___INTMAX_MAX__                = 9223372036854775807
	Xstdbool___INTPTR_MAX__                = 9223372036854775807
	Xstdbool___INT_FAST16_MAX__            = 9223372036854775807
	Xstdbool___INT_FAST32_MAX__            = 9223372036854775807
	Xstdbool___INT_FAST64_MAX__            = 9223372036854775807
	Xstdbool___INT_FAST8_MAX__             = 127
	Xstdbool___INT_LEAST16_MAX__           = 32767
	Xstdbool___INT_LEAST32_MAX__           = 2147483647
	Xstdbool___INT_LEAST32_TYPE__          = 0
	Xstdbool___INT_LEAST64_MAX__           = 9223372036854775807
	Xstdbool___INT_LEAST8_MAX__            = 127
	Xstdbool___INT_MAX__                   = 2147483647
	Xstdbool___LDBL_DENORM_MIN__           = 0
	Xstdbool___LDBL_DIG__                  = 18
	Xstdbool___LDBL_EPSILON__              = 1.0842021724855044e-19
	Xstdbool___LDBL_HAS_DENORM__           = 1
	Xstdbool___LDBL_HAS_INFINITY__         = 1
	Xstdbool___LDBL_HAS_QUIET_NAN__        = 1
	Xstdbool___LDBL_MANT_DIG__             = 64
	Xstdbool___LDBL_MAX_10_EXP__           = 4932
	Xstdbool___LDBL_MAX_EXP__              = 16384
	Xstdbool___LDBL_MAX__                  = 0
	Xstdbool___LDBL_MIN_10_EXP__           = -4931
	Xstdbool___LDBL_MIN_EXP__              = -16381
	Xstdbool___LDBL_MIN__                  = 0
	Xstdbool___LONG_LONG_MAX__             = 9223372036854775807
	Xstdbool___LONG_MAX__                  = 9223372036854775807
	Xstdbool___LP64__                      = 1
	Xstdbool___MMX__                       = 1
	Xstdbool___NO_INLINE__                 = 1
	Xstdbool___ORDER_BIG_ENDIAN__          = 4321
	Xstdbool___ORDER_LITTLE_ENDIAN__       = 1234
	Xstdbool___ORDER_PDP_ENDIAN__          = 3412
	Xstdbool___PIC__                       = 2
	Xstdbool___PIE__                       = 2
	Xstdbool___PRAGMA_REDEFINE_EXTNAME     = 1
	Xstdbool___PTRDIFF_MAX__               = 9223372036854775807
	Xstdbool___REGISTER_PREFIX__           = true
	Xstdbool___SCHAR_MAX__                 = 127
	Xstdbool___SEG_FS                      = 1
	Xstdbool___SEG_GS                      = 1
	Xstdbool___SHRT_MAX__                  = 32767
	Xstdbool___SIG_ATOMIC_MAX__            = 2147483647
	Xstdbool___SIG_ATOMIC_MIN__            = -2147483648
	Xstdbool___SIG_ATOMIC_TYPE__           = 0
	Xstdbool___SIZEOF_DOUBLE__             = 8
	Xstdbool___SIZEOF_FLOAT128__           = 16
	Xstdbool___SIZEOF_FLOAT80__            = 16
	Xstdbool___SIZEOF_FLOAT__              = 4
	Xstdbool___SIZEOF_INT__                = 4
	Xstdbool___SIZEOF_LONG_DOUBLE__        = 16
	Xstdbool___SIZEOF_LONG_LONG__          = 8
	Xstdbool___SIZEOF_LONG__               = 8
	Xstdbool___SIZEOF_POINTER__            = 8
	Xstdbool___SIZEOF_PTRDIFF_T__          = 8
	Xstdbool___SIZEOF_SHORT__              = 2
	Xstdbool___SIZEOF_SIZE_T__             = 8
	Xstdbool___SIZEOF_WCHAR_T__            = 4
	Xstdbool___SIZEOF_WINT_T__             = 4
	Xstdbool___SIZE_MAX__                  = 18446744073709551615
	Xstdbool___SSE2_MATH__                 = 1
	Xstdbool___SSE2__                      = 1
	Xstdbool___SSE_MATH__                  = 1
	Xstdbool___SSE__                       = 1
	Xstdbool___SSP_STRONG__                = 3
	Xstdbool___STDC_HOSTED__               = 1
	Xstdbool___STDC_IEC_559_COMPLEX__      = 1
	Xstdbool___STDC_IEC_559__              = 1
	Xstdbool___STDC_ISO_10646__            = 201505
	Xstdbool___STDC_NO_THREADS__           = 1
	Xstdbool___STDC_VERSION__              = 199901
	Xstdbool___STDC__                      = 1
	Xstdbool___STRICT_ANSI__               = 1
	Xstdbool___UINT16_MAX__                = 65535
	Xstdbool___UINT32_MAX__                = 4294967295
	Xstdbool___UINT64_MAX__                = 18446744073709551615
	Xstdbool___UINT8_MAX__                 = 255
	Xstdbool___UINTMAX_MAX__               = 18446744073709551615
	Xstdbool___UINTPTR_MAX__               = 18446744073709551615
	Xstdbool___UINT_FAST16_MAX__           = 18446744073709551615
	Xstdbool___UINT_FAST32_MAX__           = 18446744073709551615
	Xstdbool___UINT_FAST64_MAX__           = 18446744073709551615
	Xstdbool___UINT_FAST8_MAX__            = 255
	Xstdbool___UINT_LEAST16_MAX__          = 65535
	Xstdbool___UINT_LEAST32_MAX__          = 4294967295
	Xstdbool___UINT_LEAST64_MAX__          = 18446744073709551615
	Xstdbool___UINT_LEAST8_MAX__           = 255
	Xstdbool___USER_LABEL_PREFIX__         = true
	Xstdbool___VERSION__                   = 39831
	Xstdbool___WCHAR_MAX__                 = 2147483647
	Xstdbool___WCHAR_MIN__                 = -2147483648
	Xstdbool___WCHAR_TYPE__                = 0
	Xstdbool___WINT_MAX__                  = 4294967295
	Xstdbool___WINT_MIN__                  = 0
	Xstdbool___amd64                       = 1
	Xstdbool___amd64__                     = 1
	Xstdbool___arch__                      = 0
	Xstdbool___bool_true_false_are_defined = 1
	Xstdbool___code_model_small__          = 1
	Xstdbool___complex__                   = 0
	Xstdbool___const                       = 0
	Xstdbool___extension__                 = true
	Xstdbool___inline                      = 0
	Xstdbool___k8                          = 1
	Xstdbool___k8__                        = 1
	Xstdbool___linux                       = 1
	Xstdbool___linux__                     = 1
	Xstdbool___os__                        = 0
	Xstdbool___pic__                       = 2
	Xstdbool___pie__                       = 2
	Xstdbool___restrict                    = 0
	Xstdbool___unix                        = 1
	Xstdbool___unix__                      = 1
	Xstdbool___volatile                    = 0
	Xstdbool___x86_64                      = 1
	Xstdbool___x86_64__                    = 1
	Xstdbool_bool                          = 0
	Xstdbool_false                         = 0
	Xstdbool_true                          = 1
)
