// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

package libc

const (
	Xstddef__BUILTIN_H_               = true
	Xstddef__LP64                     = 1
	Xstddef__PREDEFINED_H_            = true
	Xstddef__STDC_PREDEF_H            = 1
	Xstddef__STDDEF_H_                = true
	Xstddef___ATOMIC_ACQUIRE          = 2
	Xstddef___ATOMIC_ACQ_REL          = 4
	Xstddef___ATOMIC_CONSUME          = 1
	Xstddef___ATOMIC_HLE_ACQUIRE      = 65536
	Xstddef___ATOMIC_HLE_RELEASE      = 131072
	Xstddef___ATOMIC_RELAXED          = 0
	Xstddef___ATOMIC_RELEASE          = 3
	Xstddef___ATOMIC_SEQ_CST          = 5
	Xstddef___BIGGEST_ALIGNMENT__     = 16
	Xstddef___BYTE_ORDER__            = 1234
	Xstddef___CHAR_BIT__              = 8
	Xstddef___DBL_DECIMAL_DIG__       = 17
	Xstddef___DBL_DIG__               = 15
	Xstddef___DBL_HAS_DENORM__        = 1
	Xstddef___DBL_HAS_INFINITY__      = 1
	Xstddef___DBL_HAS_QUIET_NAN__     = 1
	Xstddef___DBL_MANT_DIG__          = 53
	Xstddef___DBL_MAX_10_EXP__        = 308
	Xstddef___DBL_MAX_EXP__           = 1024
	Xstddef___DBL_MIN_10_EXP__        = -307
	Xstddef___DBL_MIN_EXP__           = -1021
	Xstddef___DEC128_MANT_DIG__       = 34
	Xstddef___DEC128_MAX_EXP__        = 6145
	Xstddef___DEC128_MIN_EXP__        = -6142
	Xstddef___DEC32_MANT_DIG__        = 7
	Xstddef___DEC32_MAX_EXP__         = 97
	Xstddef___DEC32_MIN_EXP__         = -94
	Xstddef___DEC64_MANT_DIG__        = 16
	Xstddef___DEC64_MAX_EXP__         = 385
	Xstddef___DEC64_MIN_EXP__         = -382
	Xstddef___DECIMAL_BID_FORMAT__    = 1
	Xstddef___DECIMAL_DIG__           = 21
	Xstddef___DEC_EVAL_METHOD__       = 2
	Xstddef___FINITE_MATH_ONLY__      = 0
	Xstddef___FLOAT_WORD_ORDER__      = 1234
	Xstddef___FLT_DECIMAL_DIG__       = 9
	Xstddef___FLT_DENORM_MIN__        = 1e-45
	Xstddef___FLT_DIG__               = 6
	Xstddef___FLT_EPSILON__           = 1.1920929e-07
	Xstddef___FLT_EVAL_METHOD__       = 0
	Xstddef___FLT_HAS_DENORM__        = 1
	Xstddef___FLT_HAS_INFINITY__      = 1
	Xstddef___FLT_HAS_QUIET_NAN__     = 1
	Xstddef___FLT_MANT_DIG__          = 24
	Xstddef___FLT_MAX_10_EXP__        = 38
	Xstddef___FLT_MAX_EXP__           = 128
	Xstddef___FLT_MAX__               = 3.4028235e+38
	Xstddef___FLT_MIN_10_EXP__        = -37
	Xstddef___FLT_MIN_EXP__           = -125
	Xstddef___FLT_MIN__               = 1.1754944e-38
	Xstddef___FLT_RADIX__             = 2
	Xstddef___FUNCTION__              = 0
	Xstddef___FXSR__                  = 1
	Xstddef___GXX_ABI_VERSION         = 1010
	Xstddef___INT16_MAX__             = 32767
	Xstddef___INT32_MAX__             = 2147483647
	Xstddef___INT32_TYPE__            = 0
	Xstddef___INT64_MAX__             = 9223372036854775807
	Xstddef___INT8_MAX__              = 127
	Xstddef___INTMAX_MAX__            = 9223372036854775807
	Xstddef___INTPTR_MAX__            = 9223372036854775807
	Xstddef___INT_FAST16_MAX__        = 9223372036854775807
	Xstddef___INT_FAST32_MAX__        = 9223372036854775807
	Xstddef___INT_FAST64_MAX__        = 9223372036854775807
	Xstddef___INT_FAST8_MAX__         = 127
	Xstddef___INT_LEAST16_MAX__       = 32767
	Xstddef___INT_LEAST32_MAX__       = 2147483647
	Xstddef___INT_LEAST32_TYPE__      = 0
	Xstddef___INT_LEAST64_MAX__       = 9223372036854775807
	Xstddef___INT_LEAST8_MAX__        = 127
	Xstddef___INT_MAX__               = 2147483647
	Xstddef___LDBL_DENORM_MIN__       = 0
	Xstddef___LDBL_DIG__              = 18
	Xstddef___LDBL_EPSILON__          = 1.0842021724855044e-19
	Xstddef___LDBL_HAS_DENORM__       = 1
	Xstddef___LDBL_HAS_INFINITY__     = 1
	Xstddef___LDBL_HAS_QUIET_NAN__    = 1
	Xstddef___LDBL_MANT_DIG__         = 64
	Xstddef___LDBL_MAX_10_EXP__       = 4932
	Xstddef___LDBL_MAX_EXP__          = 16384
	Xstddef___LDBL_MAX__              = 0
	Xstddef___LDBL_MIN_10_EXP__       = -4931
	Xstddef___LDBL_MIN_EXP__          = -16381
	Xstddef___LDBL_MIN__              = 0
	Xstddef___LONG_LONG_MAX__         = 9223372036854775807
	Xstddef___LONG_MAX__              = 9223372036854775807
	Xstddef___LP64__                  = 1
	Xstddef___MMX__                   = 1
	Xstddef___NO_INLINE__             = 1
	Xstddef___ORDER_BIG_ENDIAN__      = 4321
	Xstddef___ORDER_LITTLE_ENDIAN__   = 1234
	Xstddef___ORDER_PDP_ENDIAN__      = 3412
	Xstddef___PIC__                   = 2
	Xstddef___PIE__                   = 2
	Xstddef___PRAGMA_REDEFINE_EXTNAME = 1
	Xstddef___PTRDIFF_MAX__           = 9223372036854775807
	Xstddef___REGISTER_PREFIX__       = true
	Xstddef___SCHAR_MAX__             = 127
	Xstddef___SEG_FS                  = 1
	Xstddef___SEG_GS                  = 1
	Xstddef___SHRT_MAX__              = 32767
	Xstddef___SIG_ATOMIC_MAX__        = 2147483647
	Xstddef___SIG_ATOMIC_MIN__        = -2147483648
	Xstddef___SIG_ATOMIC_TYPE__       = 0
	Xstddef___SIZEOF_DOUBLE__         = 8
	Xstddef___SIZEOF_FLOAT128__       = 16
	Xstddef___SIZEOF_FLOAT80__        = 16
	Xstddef___SIZEOF_FLOAT__          = 4
	Xstddef___SIZEOF_INT__            = 4
	Xstddef___SIZEOF_LONG_DOUBLE__    = 16
	Xstddef___SIZEOF_LONG_LONG__      = 8
	Xstddef___SIZEOF_LONG__           = 8
	Xstddef___SIZEOF_POINTER__        = 8
	Xstddef___SIZEOF_PTRDIFF_T__      = 8
	Xstddef___SIZEOF_SHORT__          = 2
	Xstddef___SIZEOF_SIZE_T__         = 8
	Xstddef___SIZEOF_WCHAR_T__        = 4
	Xstddef___SIZEOF_WINT_T__         = 4
	Xstddef___SIZE_MAX__              = 18446744073709551615
	Xstddef___SSE2_MATH__             = 1
	Xstddef___SSE2__                  = 1
	Xstddef___SSE_MATH__              = 1
	Xstddef___SSE__                   = 1
	Xstddef___SSP_STRONG__            = 3
	Xstddef___STDC_HOSTED__           = 1
	Xstddef___STDC_IEC_559_COMPLEX__  = 1
	Xstddef___STDC_IEC_559__          = 1
	Xstddef___STDC_ISO_10646__        = 201505
	Xstddef___STDC_NO_THREADS__       = 1
	Xstddef___STDC_VERSION__          = 199901
	Xstddef___STDC__                  = 1
	Xstddef___STRICT_ANSI__           = 1
	Xstddef___UINT16_MAX__            = 65535
	Xstddef___UINT32_MAX__            = 4294967295
	Xstddef___UINT64_MAX__            = 18446744073709551615
	Xstddef___UINT8_MAX__             = 255
	Xstddef___UINTMAX_MAX__           = 18446744073709551615
	Xstddef___UINTPTR_MAX__           = 18446744073709551615
	Xstddef___UINT_FAST16_MAX__       = 18446744073709551615
	Xstddef___UINT_FAST32_MAX__       = 18446744073709551615
	Xstddef___UINT_FAST64_MAX__       = 18446744073709551615
	Xstddef___UINT_FAST8_MAX__        = 255
	Xstddef___UINT_LEAST16_MAX__      = 65535
	Xstddef___UINT_LEAST32_MAX__      = 4294967295
	Xstddef___UINT_LEAST64_MAX__      = 18446744073709551615
	Xstddef___UINT_LEAST8_MAX__       = 255
	Xstddef___USER_LABEL_PREFIX__     = true
	Xstddef___VERSION__               = 39831
	Xstddef___WCHAR_MAX__             = 2147483647
	Xstddef___WCHAR_MIN__             = -2147483648
	Xstddef___WCHAR_TYPE__            = 0
	Xstddef___WINT_MAX__              = 4294967295
	Xstddef___WINT_MIN__              = 0
	Xstddef___amd64                   = 1
	Xstddef___amd64__                 = 1
	Xstddef___arch__                  = 0
	Xstddef___code_model_small__      = 1
	Xstddef___complex__               = 0
	Xstddef___const                   = 0
	Xstddef___extension__             = true
	Xstddef___inline                  = 0
	Xstddef___k8                      = 1
	Xstddef___k8__                    = 1
	Xstddef___linux                   = 1
	Xstddef___linux__                 = 1
	Xstddef___os__                    = 0
	Xstddef___pic__                   = 2
	Xstddef___pie__                   = 2
	Xstddef___restrict                = 0
	Xstddef___unix                    = 1
	Xstddef___unix__                  = 1
	Xstddef___volatile                = 0
	Xstddef___x86_64                  = 1
	Xstddef___x86_64__                = 1
)
