// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/wchar.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1995-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/libio.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.
   Written by Per Bothner <bothner@cygnus.com>.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.

   As a special exception, if you link the code in this file with
   files compiled with a GNU compiler to produce an executable,
   that does not cause the resulting executable to be covered by
   the GNU Lesser General Public License.  This exception does not
   however invalidate any other reasons why the executable file
   might be covered by the GNU Lesser General Public License.
   This exception applies to code released by its copyright holders
   in files containing the exception.  */

package libc

const (
	Xstdio_BUFSIZ                    = 8192
	Xstdio_EOF                       = -1
	Xstdio_P_tmpdir                  = 290997
	Xstdio_SEEK_CUR                  = 1
	Xstdio_SEEK_END                  = 2
	Xstdio_SEEK_SET                  = 0
	Xstdio__BITS_TYPES_H             = 1
	Xstdio__BUILTIN_H_               = true
	Xstdio__G_BUFSIZ                 = 8192
	Xstdio__G_HAVE_MMAP              = 1
	Xstdio__G_HAVE_MREMAP            = 1
	Xstdio__G_HAVE_ST_BLKSIZE        = 0
	Xstdio__G_IO_IO_FILE_VERSION     = 131073
	Xstdio__G_config_h               = 1
	Xstdio__G_va_list                = 0
	Xstdio__IOFBF                    = 0
	Xstdio__IOLBF                    = 1
	Xstdio__IONBF                    = 2
	Xstdio__IOS_APPEND               = 8
	Xstdio__IOS_ATEND                = 4
	Xstdio__IOS_BIN                  = 128
	Xstdio__IOS_INPUT                = 1
	Xstdio__IOS_NOCREATE             = 32
	Xstdio__IOS_NOREPLACE            = 64
	Xstdio__IOS_OUTPUT               = 2
	Xstdio__IOS_TRUNC                = 16
	Xstdio__IO_BAD_SEEN              = 16384
	Xstdio__IO_BOOLALPHA             = 65536
	Xstdio__IO_BUFSIZ                = 8192
	Xstdio__IO_CURRENTLY_PUTTING     = 2048
	Xstdio__IO_DEC                   = 16
	Xstdio__IO_DELETE_DONT_CLOSE     = 64
	Xstdio__IO_DONT_CLOSE            = 32768
	Xstdio__IO_EOF_SEEN              = 16
	Xstdio__IO_ERR_SEEN              = 32
	Xstdio__IO_FIXED                 = 4096
	Xstdio__IO_FLAGS2_MMAP           = 1
	Xstdio__IO_FLAGS2_NOTCANCEL      = 2
	Xstdio__IO_FLAGS2_USER_WBUF      = 8
	Xstdio__IO_HAVE_ST_BLKSIZE       = 0
	Xstdio__IO_HEX                   = 64
	Xstdio__IO_INTERNAL              = 8
	Xstdio__IO_IN_BACKUP             = 256
	Xstdio__IO_IS_APPENDING          = 4096
	Xstdio__IO_IS_FILEBUF            = 8192
	Xstdio__IO_LEFT                  = 2
	Xstdio__IO_LINE_BUF              = 512
	Xstdio__IO_LINKED                = 128
	Xstdio__IO_MAGIC                 = 4222418944
	Xstdio__IO_MAGIC_MASK            = 4294901760
	Xstdio__IO_NO_READS              = 4
	Xstdio__IO_NO_WRITES             = 8
	Xstdio__IO_OCT                   = 32
	Xstdio__IO_RIGHT                 = 4
	Xstdio__IO_SCIENTIFIC            = 2048
	Xstdio__IO_SHOWBASE              = 128
	Xstdio__IO_SHOWPOINT             = 256
	Xstdio__IO_SHOWPOS               = 1024
	Xstdio__IO_SKIPWS                = 1
	Xstdio__IO_STDIO                 = 16384
	Xstdio__IO_TIED_PUT_GET          = 1024
	Xstdio__IO_UNBUFFERED            = 2
	Xstdio__IO_UNIFIED_JUMPTABLES    = 1
	Xstdio__IO_UNITBUF               = 8192
	Xstdio__IO_UPPERCASE             = 512
	Xstdio__IO_USER_BUF              = 1
	Xstdio__IO_USER_LOCK             = 32768
	Xstdio__IO_file_flags            = 0
	Xstdio__IO_fpos64_t              = 0
	Xstdio__IO_fpos_t                = 0
	Xstdio__IO_iconv_t               = 0
	Xstdio__IO_off64_t               = 0
	Xstdio__IO_off_t                 = 0
	Xstdio__IO_pid_t                 = 0
	Xstdio__IO_size_t                = 0
	Xstdio__IO_ssize_t               = 0
	Xstdio__IO_uid_t                 = 0
	Xstdio__IO_va_list               = 0
	Xstdio__IO_wint_t                = 0
	Xstdio__LP64                     = 1
	Xstdio__OLD_STDIO_MAGIC          = 4206624768
	Xstdio__PREDEFINED_H_            = true
	Xstdio__STDC_PREDEF_H            = 1
	Xstdio__STDIO_H                  = 1
	Xstdio__STDIO_H_                 = true
	Xstdio___ATOMIC_ACQUIRE          = 2
	Xstdio___ATOMIC_ACQ_REL          = 4
	Xstdio___ATOMIC_CONSUME          = 1
	Xstdio___ATOMIC_HLE_ACQUIRE      = 65536
	Xstdio___ATOMIC_HLE_RELEASE      = 131072
	Xstdio___ATOMIC_RELAXED          = 0
	Xstdio___ATOMIC_RELEASE          = 3
	Xstdio___ATOMIC_SEQ_CST          = 5
	Xstdio___BIGGEST_ALIGNMENT__     = 16
	Xstdio___BYTE_ORDER__            = 1234
	Xstdio___CHAR_BIT__              = 8
	Xstdio___DBL_DECIMAL_DIG__       = 17
	Xstdio___DBL_DIG__               = 15
	Xstdio___DBL_HAS_DENORM__        = 1
	Xstdio___DBL_HAS_INFINITY__      = 1
	Xstdio___DBL_HAS_QUIET_NAN__     = 1
	Xstdio___DBL_MANT_DIG__          = 53
	Xstdio___DBL_MAX_10_EXP__        = 308
	Xstdio___DBL_MAX_EXP__           = 1024
	Xstdio___DBL_MIN_10_EXP__        = -307
	Xstdio___DBL_MIN_EXP__           = -1021
	Xstdio___DEC128_MANT_DIG__       = 34
	Xstdio___DEC128_MAX_EXP__        = 6145
	Xstdio___DEC128_MIN_EXP__        = -6142
	Xstdio___DEC32_MANT_DIG__        = 7
	Xstdio___DEC32_MAX_EXP__         = 97
	Xstdio___DEC32_MIN_EXP__         = -94
	Xstdio___DEC64_MANT_DIG__        = 16
	Xstdio___DEC64_MAX_EXP__         = 385
	Xstdio___DEC64_MIN_EXP__         = -382
	Xstdio___DECIMAL_BID_FORMAT__    = 1
	Xstdio___DECIMAL_DIG__           = 21
	Xstdio___DEC_EVAL_METHOD__       = 2
	Xstdio___FILE_defined            = 1
	Xstdio___FINITE_MATH_ONLY__      = 0
	Xstdio___FLOAT_WORD_ORDER__      = 1234
	Xstdio___FLT_DECIMAL_DIG__       = 9
	Xstdio___FLT_DENORM_MIN__        = 1e-45
	Xstdio___FLT_DIG__               = 6
	Xstdio___FLT_EPSILON__           = 1.1920929e-07
	Xstdio___FLT_EVAL_METHOD__       = 0
	Xstdio___FLT_HAS_DENORM__        = 1
	Xstdio___FLT_HAS_INFINITY__      = 1
	Xstdio___FLT_HAS_QUIET_NAN__     = 1
	Xstdio___FLT_MANT_DIG__          = 24
	Xstdio___FLT_MAX_10_EXP__        = 38
	Xstdio___FLT_MAX_EXP__           = 128
	Xstdio___FLT_MAX__               = 3.4028235e+38
	Xstdio___FLT_MIN_10_EXP__        = -37
	Xstdio___FLT_MIN_EXP__           = -125
	Xstdio___FLT_MIN__               = 1.1754944e-38
	Xstdio___FLT_RADIX__             = 2
	Xstdio___FUNCTION__              = 0
	Xstdio___FXSR__                  = 1
	Xstdio___GXX_ABI_VERSION         = 1010
	Xstdio___INT16_MAX__             = 32767
	Xstdio___INT32_MAX__             = 2147483647
	Xstdio___INT32_TYPE__            = 0
	Xstdio___INT64_MAX__             = 9223372036854775807
	Xstdio___INT8_MAX__              = 127
	Xstdio___INTMAX_MAX__            = 9223372036854775807
	Xstdio___INTPTR_MAX__            = 9223372036854775807
	Xstdio___INT_FAST16_MAX__        = 9223372036854775807
	Xstdio___INT_FAST32_MAX__        = 9223372036854775807
	Xstdio___INT_FAST64_MAX__        = 9223372036854775807
	Xstdio___INT_FAST8_MAX__         = 127
	Xstdio___INT_LEAST16_MAX__       = 32767
	Xstdio___INT_LEAST32_MAX__       = 2147483647
	Xstdio___INT_LEAST32_TYPE__      = 0
	Xstdio___INT_LEAST64_MAX__       = 9223372036854775807
	Xstdio___INT_LEAST8_MAX__        = 127
	Xstdio___INT_MAX__               = 2147483647
	Xstdio___LDBL_DENORM_MIN__       = 0
	Xstdio___LDBL_DIG__              = 18
	Xstdio___LDBL_EPSILON__          = 1.0842021724855044e-19
	Xstdio___LDBL_HAS_DENORM__       = 1
	Xstdio___LDBL_HAS_INFINITY__     = 1
	Xstdio___LDBL_HAS_QUIET_NAN__    = 1
	Xstdio___LDBL_MANT_DIG__         = 64
	Xstdio___LDBL_MAX_10_EXP__       = 4932
	Xstdio___LDBL_MAX_EXP__          = 16384
	Xstdio___LDBL_MAX__              = 0
	Xstdio___LDBL_MIN_10_EXP__       = -4931
	Xstdio___LDBL_MIN_EXP__          = -16381
	Xstdio___LDBL_MIN__              = 0
	Xstdio___LONG_LONG_MAX__         = 9223372036854775807
	Xstdio___LONG_MAX__              = 9223372036854775807
	Xstdio___LP64__                  = 1
	Xstdio___MMX__                   = 1
	Xstdio___NO_INLINE__             = 1
	Xstdio___ORDER_BIG_ENDIAN__      = 4321
	Xstdio___ORDER_LITTLE_ENDIAN__   = 1234
	Xstdio___ORDER_PDP_ENDIAN__      = 3412
	Xstdio___PIC__                   = 2
	Xstdio___PIE__                   = 2
	Xstdio___PRAGMA_REDEFINE_EXTNAME = 1
	Xstdio___PTRDIFF_MAX__           = 9223372036854775807
	Xstdio___REGISTER_PREFIX__       = true
	Xstdio___S32_TYPE                = 0
	Xstdio___SCHAR_MAX__             = 127
	Xstdio___SEG_FS                  = 1
	Xstdio___SEG_GS                  = 1
	Xstdio___SHRT_MAX__              = 32767
	Xstdio___SIG_ATOMIC_MAX__        = 2147483647
	Xstdio___SIG_ATOMIC_MIN__        = -2147483648
	Xstdio___SIG_ATOMIC_TYPE__       = 0
	Xstdio___SIZEOF_DOUBLE__         = 8
	Xstdio___SIZEOF_FLOAT128__       = 16
	Xstdio___SIZEOF_FLOAT80__        = 16
	Xstdio___SIZEOF_FLOAT__          = 4
	Xstdio___SIZEOF_INT__            = 4
	Xstdio___SIZEOF_LONG_DOUBLE__    = 16
	Xstdio___SIZEOF_LONG_LONG__      = 8
	Xstdio___SIZEOF_LONG__           = 8
	Xstdio___SIZEOF_POINTER__        = 8
	Xstdio___SIZEOF_PTRDIFF_T__      = 8
	Xstdio___SIZEOF_SHORT__          = 2
	Xstdio___SIZEOF_SIZE_T__         = 8
	Xstdio___SIZEOF_WCHAR_T__        = 4
	Xstdio___SIZEOF_WINT_T__         = 4
	Xstdio___SIZE_MAX__              = 18446744073709551615
	Xstdio___SLONG32_TYPE            = 0
	Xstdio___SSE2_MATH__             = 1
	Xstdio___SSE2__                  = 1
	Xstdio___SSE_MATH__              = 1
	Xstdio___SSE__                   = 1
	Xstdio___SSP_STRONG__            = 3
	Xstdio___STDC_HOSTED__           = 1
	Xstdio___STDC_IEC_559_COMPLEX__  = 1
	Xstdio___STDC_IEC_559__          = 1
	Xstdio___STDC_ISO_10646__        = 201505
	Xstdio___STDC_NO_THREADS__       = 1
	Xstdio___STDC_VERSION__          = 199901
	Xstdio___STDC__                  = 1
	Xstdio___STRICT_ANSI__           = 1
	Xstdio___UINT16_MAX__            = 65535
	Xstdio___UINT32_MAX__            = 4294967295
	Xstdio___UINT64_MAX__            = 18446744073709551615
	Xstdio___UINT8_MAX__             = 255
	Xstdio___UINTMAX_MAX__           = 18446744073709551615
	Xstdio___UINTPTR_MAX__           = 18446744073709551615
	Xstdio___UINT_FAST16_MAX__       = 18446744073709551615
	Xstdio___UINT_FAST32_MAX__       = 18446744073709551615
	Xstdio___UINT_FAST64_MAX__       = 18446744073709551615
	Xstdio___UINT_FAST8_MAX__        = 255
	Xstdio___UINT_LEAST16_MAX__      = 65535
	Xstdio___UINT_LEAST32_MAX__      = 4294967295
	Xstdio___UINT_LEAST64_MAX__      = 18446744073709551615
	Xstdio___UINT_LEAST8_MAX__       = 255
	Xstdio___USER_LABEL_PREFIX__     = true
	Xstdio___VERSION__               = 39831
	Xstdio___WCHAR_MAX__             = 2147483647
	Xstdio___WCHAR_MIN__             = -2147483648
	Xstdio___WCHAR_TYPE__            = 0
	Xstdio___WINT_MAX__              = 4294967295
	Xstdio___WINT_MIN__              = 0
	Xstdio_____FILE_defined          = 1
	Xstdio_____mbstate_t_defined     = 1
	Xstdio___amd64                   = 1
	Xstdio___amd64__                 = 1
	Xstdio___arch__                  = 0
	Xstdio___code_model_small__      = 1
	Xstdio___complex__               = 0
	Xstdio___const                   = 0
	Xstdio___extension__             = true
	Xstdio___inline                  = 0
	Xstdio___k8                      = 1
	Xstdio___k8__                    = 1
	Xstdio___linux                   = 1
	Xstdio___linux__                 = 1
	Xstdio___os__                    = 0
	Xstdio___pic__                   = 2
	Xstdio___pie__                   = 2
	Xstdio___restrict                = 0
	Xstdio___unix                    = 1
	Xstdio___unix__                  = 1
	Xstdio___volatile                = 0
	Xstdio___x86_64                  = 1
	Xstdio___x86_64__                = 1
	Xstdio_fscanf                    = 0
	Xstdio_scanf                     = 0
	Xstdio_sscanf                    = 0
	Xstdio_vfscanf                   = 0
	Xstdio_vscanf                    = 0
	Xstdio_vsscanf                   = 0
	Xstdio___codecvt_error           = 2
	Xstdio___codecvt_noconv          = 3
	Xstdio___codecvt_ok              = 0
	Xstdio___codecvt_partial         = 1
)
