// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/stdint.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1997-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package libc

const (
	Stdint_INT16_MAX        = 32767
	Stdint_INT16_MIN        = -32768
	Stdint_INT32_MAX        = 2147483647
	Stdint_INT32_MIN        = 2147483648
	Stdint_INT64_MAX        = 9223372036854775807
	Stdint_INT64_MIN        = -9223372036854775808
	Stdint_INT8_MAX         = 127
	Stdint_INT8_MIN         = -128
	Stdint_INTMAX_MAX       = 9223372036854775807
	Stdint_INTMAX_MIN       = -9223372036854775808
	Stdint_INTPTR_MAX       = 9223372036854775807
	Stdint_INTPTR_MIN       = -9223372036854775808
	Stdint_INT_FAST16_MAX   = 9223372036854775807
	Stdint_INT_FAST16_MIN   = -9223372036854775808
	Stdint_INT_FAST32_MAX   = 9223372036854775807
	Stdint_INT_FAST32_MIN   = -9223372036854775808
	Stdint_INT_FAST64_MAX   = 9223372036854775807
	Stdint_INT_FAST64_MIN   = -9223372036854775808
	Stdint_INT_FAST8_MAX    = 127
	Stdint_INT_FAST8_MIN    = -128
	Stdint_INT_LEAST16_MAX  = 32767
	Stdint_INT_LEAST16_MIN  = -32768
	Stdint_INT_LEAST32_MAX  = 2147483647
	Stdint_INT_LEAST32_MIN  = 2147483648
	Stdint_INT_LEAST64_MAX  = 9223372036854775807
	Stdint_INT_LEAST64_MIN  = -9223372036854775808
	Stdint_INT_LEAST8_MAX   = 127
	Stdint_INT_LEAST8_MIN   = -128
	Stdint_PTRDIFF_MAX      = 9223372036854775807
	Stdint_PTRDIFF_MIN      = -9223372036854775808
	Stdint_SIG_ATOMIC_MAX   = 2147483647
	Stdint_SIG_ATOMIC_MIN   = 2147483648
	Stdint_SIZE_MAX         = 18446744073709551615
	Stdint_UINT16_MAX       = 65535
	Stdint_UINT32_MAX       = 4294967295
	Stdint_UINT64_MAX       = 18446744073709551615
	Stdint_UINT8_MAX        = 255
	Stdint_UINTMAX_MAX      = 18446744073709551615
	Stdint_UINTPTR_MAX      = 18446744073709551615
	Stdint_UINT_FAST16_MAX  = 18446744073709551615
	Stdint_UINT_FAST32_MAX  = 18446744073709551615
	Stdint_UINT_FAST64_MAX  = 18446744073709551615
	Stdint_UINT_FAST8_MAX   = 255
	Stdint_UINT_LEAST16_MAX = 65535
	Stdint_UINT_LEAST32_MAX = 4294967295
	Stdint_UINT_LEAST64_MAX = 18446744073709551615
	Stdint_UINT_LEAST8_MAX  = 255
	Stdint_WCHAR_MAX        = 0
	Stdint_WCHAR_MIN        = 0
	Stdint_WINT_MAX         = 4294967295
	Stdint_WINT_MIN         = 0
	Stdint__STDINT_H        = 1
)
