// Code generated by running "go generate". DO NOT EDIT.

	// +build ignore
	
	// BEGIN OF FILE m:\mingw\x86_64-w64-mingw32\include\stdint.h 

typedef signed char int8_t ;
typedef unsigned char uint8_t ;
typedef short int16_t ;
typedef unsigned short uint16_t ;
typedef int int32_t ;
typedef unsigned uint32_t ;
typedef long long int64_t ;
typedef unsigned long long uint64_t ;
typedef signed char int_least8_t ;
typedef unsigned char uint_least8_t ;
typedef short int_least16_t ;
typedef unsigned short uint_least16_t ;
typedef int int_least32_t ;
typedef unsigned uint_least32_t ;
typedef long long int_least64_t ;
typedef unsigned long long uint_least64_t ;
typedef signed char int_fast8_t ;
typedef unsigned char uint_fast8_t ;
typedef short int_fast16_t ;
typedef unsigned short uint_fast16_t ;
typedef int int_fast32_t ;
typedef unsigned int uint_fast32_t ;
typedef long long int_fast64_t ;
typedef unsigned long long uint_fast64_t ;
typedef long long intmax_t ;
typedef unsigned long long uintmax_t ;
// BEGIN OF FILE m:\mingw\x86_64-w64-mingw32\include\stdint.h 

#define UINTMAX_MAX UINT64_MAX
#define INT_LEAST8_MIN INT8_MIN
#define INT_FAST32_MIN INT32_MIN
#define INT_FAST64_MAX INT64_MAX
#define INTMAX_MAX INT64_MAX
#define INT32_MAX (2147483647)
#define INTPTR_MIN INT64_MIN
#define WINT_MAX (65535u)
#define INTPTR_MAX INT64_MAX
#define UINT_LEAST64_MAX UINT64_MAX
#define UINT_FAST16_MAX UINT16_MAX
#define WINT_MIN (0u)
#define UINT64_MAX (18446744073709551615ull)
#define UINT16_C(val) ( val )
#define UINT8_MAX (255)
#define UINT_LEAST16_MAX UINT16_MAX
#define UINT16_MAX (65535)
#define INT_FAST16_MIN INT16_MIN
#define INT_LEAST64_MAX INT64_MAX
#define UINT_LEAST32_MAX UINT32_MAX
#define INT_FAST8_MIN INT8_MIN
#define PTRDIFF_MIN INT64_MIN
#define INT8_MIN (-128)
#define INTMAX_C(val) val ## LL
#define SIZE_MAX UINT64_MAX
#define INT8_MAX (127)
#define INT16_MIN (-32768)
#define INT_LEAST32_MAX INT32_MAX
#define INT32_C(val) ( INT_LEAST32_MAX - INT_LEAST32_MAX + ( val ) )
#define SIG_ATOMIC_MIN INT32_MIN
#define SIG_ATOMIC_MAX INT32_MAX
#define INT16_MAX (32767)
#define INT8_C(val) ( INT_LEAST8_MAX - INT_LEAST8_MAX + ( val ) )
#define UINT_FAST64_MAX UINT64_MAX
#define UINT8_C(val) ( val )
#define INT_LEAST64_MIN INT64_MIN
#define INT_FAST32_MAX INT32_MAX
#define UINT_FAST8_MAX UINT8_MAX
#define PTRDIFF_MAX INT64_MAX
#define WCHAR_MAX (65535u)
#define UINTPTR_MAX UINT64_MAX
#define INT64_MIN (-9223372036854775808ll)
#define INT32_MIN (-2147483648)
#define INT_FAST64_MIN INT64_MIN
#define UINT_LEAST8_MAX UINT8_MAX
#define UINT64_C(val) val ## ULL
#define INT16_C(val) ( INT_LEAST16_MAX - INT_LEAST16_MAX + ( val ) )
#define UINTMAX_C(val) val ## ULL
#define INT64_C(val) val ## LL
#define UINT_FAST32_MAX UINT32_MAX
#define INT_LEAST32_MIN INT32_MIN
#define INT_FAST8_MAX INT8_MAX
#define UINT32_MAX (4294967295u)
#define INT_FAST16_MAX INT16_MAX
#define _STDINT_H 
#define INT_LEAST8_MAX INT8_MAX
#define INTMAX_MIN INT64_MIN
#define INT_LEAST16_MIN INT16_MIN
#define WCHAR_MIN (0u)
#define UINT32_C(val) ( val ## U )
#define INT_LEAST16_MAX INT16_MAX
#define INT64_MAX (9223372036854775807ll)
