// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/stdint.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1997-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package libc

const (
	Xstdint_INT16_MAX                 = 32767
	Xstdint_INT16_MIN                 = -32768
	Xstdint_INT32_MAX                 = 2147483647
	Xstdint_INT32_MIN                 = 2147483648
	Xstdint_INT64_MAX                 = 9223372036854775807
	Xstdint_INT64_MIN                 = -9223372036854775808
	Xstdint_INT8_MAX                  = 127
	Xstdint_INT8_MIN                  = -128
	Xstdint_INTMAX_MAX                = 9223372036854775807
	Xstdint_INTMAX_MIN                = -9223372036854775808
	Xstdint_INTPTR_MAX                = 9223372036854775807
	Xstdint_INTPTR_MIN                = -9223372036854775808
	Xstdint_INT_FAST16_MAX            = 9223372036854775807
	Xstdint_INT_FAST16_MIN            = -9223372036854775808
	Xstdint_INT_FAST32_MAX            = 9223372036854775807
	Xstdint_INT_FAST32_MIN            = -9223372036854775808
	Xstdint_INT_FAST64_MAX            = 9223372036854775807
	Xstdint_INT_FAST64_MIN            = -9223372036854775808
	Xstdint_INT_FAST8_MAX             = 127
	Xstdint_INT_FAST8_MIN             = -128
	Xstdint_INT_LEAST16_MAX           = 32767
	Xstdint_INT_LEAST16_MIN           = -32768
	Xstdint_INT_LEAST32_MAX           = 2147483647
	Xstdint_INT_LEAST32_MIN           = 2147483648
	Xstdint_INT_LEAST64_MAX           = 9223372036854775807
	Xstdint_INT_LEAST64_MIN           = -9223372036854775808
	Xstdint_INT_LEAST8_MAX            = 127
	Xstdint_INT_LEAST8_MIN            = -128
	Xstdint_PTRDIFF_MAX               = 9223372036854775807
	Xstdint_PTRDIFF_MIN               = -9223372036854775808
	Xstdint_SIG_ATOMIC_MAX            = 2147483647
	Xstdint_SIG_ATOMIC_MIN            = 2147483648
	Xstdint_SIZE_MAX                  = 18446744073709551615
	Xstdint_UINT16_MAX                = 65535
	Xstdint_UINT32_MAX                = 4294967295
	Xstdint_UINT64_MAX                = 18446744073709551615
	Xstdint_UINT8_MAX                 = 255
	Xstdint_UINTMAX_MAX               = 18446744073709551615
	Xstdint_UINTPTR_MAX               = 18446744073709551615
	Xstdint_UINT_FAST16_MAX           = 18446744073709551615
	Xstdint_UINT_FAST32_MAX           = 18446744073709551615
	Xstdint_UINT_FAST64_MAX           = 18446744073709551615
	Xstdint_UINT_FAST8_MAX            = 255
	Xstdint_UINT_LEAST16_MAX          = 65535
	Xstdint_UINT_LEAST32_MAX          = 4294967295
	Xstdint_UINT_LEAST64_MAX          = 18446744073709551615
	Xstdint_UINT_LEAST8_MAX           = 255
	Xstdint_WCHAR_MAX                 = 0
	Xstdint_WCHAR_MIN                 = 0
	Xstdint_WINT_MAX                  = 4294967295
	Xstdint_WINT_MIN                  = 0
	Xstdint__BUILTIN_H_               = true
	Xstdint__LP64                     = 1
	Xstdint__PREDEFINED_H_            = true
	Xstdint__STDC_PREDEF_H            = 1
	Xstdint__STDINT_H                 = 1
	Xstdint__STDINT_H_                = true
	Xstdint___ATOMIC_ACQUIRE          = 2
	Xstdint___ATOMIC_ACQ_REL          = 4
	Xstdint___ATOMIC_CONSUME          = 1
	Xstdint___ATOMIC_HLE_ACQUIRE      = 65536
	Xstdint___ATOMIC_HLE_RELEASE      = 131072
	Xstdint___ATOMIC_RELAXED          = 0
	Xstdint___ATOMIC_RELEASE          = 3
	Xstdint___ATOMIC_SEQ_CST          = 5
	Xstdint___BIGGEST_ALIGNMENT__     = 16
	Xstdint___BYTE_ORDER__            = 1234
	Xstdint___CHAR_BIT__              = 8
	Xstdint___DBL_DECIMAL_DIG__       = 17
	Xstdint___DBL_DIG__               = 15
	Xstdint___DBL_HAS_DENORM__        = 1
	Xstdint___DBL_HAS_INFINITY__      = 1
	Xstdint___DBL_HAS_QUIET_NAN__     = 1
	Xstdint___DBL_MANT_DIG__          = 53
	Xstdint___DBL_MAX_10_EXP__        = 308
	Xstdint___DBL_MAX_EXP__           = 1024
	Xstdint___DBL_MIN_10_EXP__        = -307
	Xstdint___DBL_MIN_EXP__           = -1021
	Xstdint___DEC128_MANT_DIG__       = 34
	Xstdint___DEC128_MAX_EXP__        = 6145
	Xstdint___DEC128_MIN_EXP__        = -6142
	Xstdint___DEC32_MANT_DIG__        = 7
	Xstdint___DEC32_MAX_EXP__         = 97
	Xstdint___DEC32_MIN_EXP__         = -94
	Xstdint___DEC64_MANT_DIG__        = 16
	Xstdint___DEC64_MAX_EXP__         = 385
	Xstdint___DEC64_MIN_EXP__         = -382
	Xstdint___DECIMAL_BID_FORMAT__    = 1
	Xstdint___DECIMAL_DIG__           = 21
	Xstdint___DEC_EVAL_METHOD__       = 2
	Xstdint___FINITE_MATH_ONLY__      = 0
	Xstdint___FLOAT_WORD_ORDER__      = 1234
	Xstdint___FLT_DECIMAL_DIG__       = 9
	Xstdint___FLT_DENORM_MIN__        = 1e-45
	Xstdint___FLT_DIG__               = 6
	Xstdint___FLT_EPSILON__           = 1.1920929e-07
	Xstdint___FLT_EVAL_METHOD__       = 0
	Xstdint___FLT_HAS_DENORM__        = 1
	Xstdint___FLT_HAS_INFINITY__      = 1
	Xstdint___FLT_HAS_QUIET_NAN__     = 1
	Xstdint___FLT_MANT_DIG__          = 24
	Xstdint___FLT_MAX_10_EXP__        = 38
	Xstdint___FLT_MAX_EXP__           = 128
	Xstdint___FLT_MAX__               = 3.4028235e+38
	Xstdint___FLT_MIN_10_EXP__        = -37
	Xstdint___FLT_MIN_EXP__           = -125
	Xstdint___FLT_MIN__               = 1.1754944e-38
	Xstdint___FLT_RADIX__             = 2
	Xstdint___FUNCTION__              = 0
	Xstdint___FXSR__                  = 1
	Xstdint___GXX_ABI_VERSION         = 1010
	Xstdint___INT16_MAX__             = 32767
	Xstdint___INT32_MAX__             = 2147483647
	Xstdint___INT32_TYPE__            = 0
	Xstdint___INT64_MAX__             = 9223372036854775807
	Xstdint___INT8_MAX__              = 127
	Xstdint___INTMAX_MAX__            = 9223372036854775807
	Xstdint___INTPTR_MAX__            = 9223372036854775807
	Xstdint___INT_FAST16_MAX__        = 9223372036854775807
	Xstdint___INT_FAST32_MAX__        = 9223372036854775807
	Xstdint___INT_FAST64_MAX__        = 9223372036854775807
	Xstdint___INT_FAST8_MAX__         = 127
	Xstdint___INT_LEAST16_MAX__       = 32767
	Xstdint___INT_LEAST32_MAX__       = 2147483647
	Xstdint___INT_LEAST32_TYPE__      = 0
	Xstdint___INT_LEAST64_MAX__       = 9223372036854775807
	Xstdint___INT_LEAST8_MAX__        = 127
	Xstdint___INT_MAX__               = 2147483647
	Xstdint___LDBL_DENORM_MIN__       = 0
	Xstdint___LDBL_DIG__              = 18
	Xstdint___LDBL_EPSILON__          = 1.0842021724855044e-19
	Xstdint___LDBL_HAS_DENORM__       = 1
	Xstdint___LDBL_HAS_INFINITY__     = 1
	Xstdint___LDBL_HAS_QUIET_NAN__    = 1
	Xstdint___LDBL_MANT_DIG__         = 64
	Xstdint___LDBL_MAX_10_EXP__       = 4932
	Xstdint___LDBL_MAX_EXP__          = 16384
	Xstdint___LDBL_MAX__              = 0
	Xstdint___LDBL_MIN_10_EXP__       = -4931
	Xstdint___LDBL_MIN_EXP__          = -16381
	Xstdint___LDBL_MIN__              = 0
	Xstdint___LONG_LONG_MAX__         = 9223372036854775807
	Xstdint___LONG_MAX__              = 9223372036854775807
	Xstdint___LP64__                  = 1
	Xstdint___MMX__                   = 1
	Xstdint___NO_INLINE__             = 1
	Xstdint___ORDER_BIG_ENDIAN__      = 4321
	Xstdint___ORDER_LITTLE_ENDIAN__   = 1234
	Xstdint___ORDER_PDP_ENDIAN__      = 3412
	Xstdint___PIC__                   = 2
	Xstdint___PIE__                   = 2
	Xstdint___PRAGMA_REDEFINE_EXTNAME = 1
	Xstdint___PTRDIFF_MAX__           = 9223372036854775807
	Xstdint___REGISTER_PREFIX__       = true
	Xstdint___SCHAR_MAX__             = 127
	Xstdint___SEG_FS                  = 1
	Xstdint___SEG_GS                  = 1
	Xstdint___SHRT_MAX__              = 32767
	Xstdint___SIG_ATOMIC_MAX__        = 2147483647
	Xstdint___SIG_ATOMIC_MIN__        = -2147483648
	Xstdint___SIG_ATOMIC_TYPE__       = 0
	Xstdint___SIZEOF_DOUBLE__         = 8
	Xstdint___SIZEOF_FLOAT128__       = 16
	Xstdint___SIZEOF_FLOAT80__        = 16
	Xstdint___SIZEOF_FLOAT__          = 4
	Xstdint___SIZEOF_INT__            = 4
	Xstdint___SIZEOF_LONG_DOUBLE__    = 16
	Xstdint___SIZEOF_LONG_LONG__      = 8
	Xstdint___SIZEOF_LONG__           = 8
	Xstdint___SIZEOF_POINTER__        = 8
	Xstdint___SIZEOF_PTRDIFF_T__      = 8
	Xstdint___SIZEOF_SHORT__          = 2
	Xstdint___SIZEOF_SIZE_T__         = 8
	Xstdint___SIZEOF_WCHAR_T__        = 4
	Xstdint___SIZEOF_WINT_T__         = 4
	Xstdint___SIZE_MAX__              = 18446744073709551615
	Xstdint___SSE2_MATH__             = 1
	Xstdint___SSE2__                  = 1
	Xstdint___SSE_MATH__              = 1
	Xstdint___SSE__                   = 1
	Xstdint___SSP_STRONG__            = 3
	Xstdint___STDC_HOSTED__           = 1
	Xstdint___STDC_IEC_559_COMPLEX__  = 1
	Xstdint___STDC_IEC_559__          = 1
	Xstdint___STDC_ISO_10646__        = 201505
	Xstdint___STDC_NO_THREADS__       = 1
	Xstdint___STDC_VERSION__          = 199901
	Xstdint___STDC__                  = 1
	Xstdint___STRICT_ANSI__           = 1
	Xstdint___UINT16_MAX__            = 65535
	Xstdint___UINT32_MAX__            = 4294967295
	Xstdint___UINT64_MAX__            = 18446744073709551615
	Xstdint___UINT8_MAX__             = 255
	Xstdint___UINTMAX_MAX__           = 18446744073709551615
	Xstdint___UINTPTR_MAX__           = 18446744073709551615
	Xstdint___UINT_FAST16_MAX__       = 18446744073709551615
	Xstdint___UINT_FAST32_MAX__       = 18446744073709551615
	Xstdint___UINT_FAST64_MAX__       = 18446744073709551615
	Xstdint___UINT_FAST8_MAX__        = 255
	Xstdint___UINT_LEAST16_MAX__      = 65535
	Xstdint___UINT_LEAST32_MAX__      = 4294967295
	Xstdint___UINT_LEAST64_MAX__      = 18446744073709551615
	Xstdint___UINT_LEAST8_MAX__       = 255
	Xstdint___USER_LABEL_PREFIX__     = true
	Xstdint___VERSION__               = 39831
	Xstdint___WCHAR_MAX__             = 2147483647
	Xstdint___WCHAR_MIN__             = -2147483648
	Xstdint___WCHAR_TYPE__            = 0
	Xstdint___WINT_MAX__              = 4294967295
	Xstdint___WINT_MIN__              = 0
	Xstdint___amd64                   = 1
	Xstdint___amd64__                 = 1
	Xstdint___arch__                  = 0
	Xstdint___code_model_small__      = 1
	Xstdint___complex__               = 0
	Xstdint___const                   = 0
	Xstdint___extension__             = true
	Xstdint___inline                  = 0
	Xstdint___k8                      = 1
	Xstdint___k8__                    = 1
	Xstdint___linux                   = 1
	Xstdint___linux__                 = 1
	Xstdint___os__                    = 0
	Xstdint___pic__                   = 2
	Xstdint___pie__                   = 2
	Xstdint___restrict                = 0
	Xstdint___unix                    = 1
	Xstdint___unix__                  = 1
	Xstdint___volatile                = 0
	Xstdint___x86_64                  = 1
	Xstdint___x86_64__                = 1
)
