// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/i686-linux-gnu/6/include/stddef.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/stdlib.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package libc

const (
	Xstdlib_EXIT_FAILURE              = 1
	Xstdlib_EXIT_SUCCESS              = 0
	Xstdlib_RAND_MAX                  = 2147483647
	Xstdlib__BUILTIN_H_               = true
	Xstdlib__PREDEFINED_H_            = true
	Xstdlib__STDC_PREDEF_H            = 1
	Xstdlib__STDLIB_H                 = 1
	Xstdlib__STDLIB_H_                = true
	Xstdlib___ATOMIC_ACQUIRE          = 2
	Xstdlib___ATOMIC_ACQ_REL          = 4
	Xstdlib___ATOMIC_CONSUME          = 1
	Xstdlib___ATOMIC_HLE_ACQUIRE      = 65536
	Xstdlib___ATOMIC_HLE_RELEASE      = 131072
	Xstdlib___ATOMIC_RELAXED          = 0
	Xstdlib___ATOMIC_RELEASE          = 3
	Xstdlib___ATOMIC_SEQ_CST          = 5
	Xstdlib___BIGGEST_ALIGNMENT__     = 16
	Xstdlib___BYTE_ORDER__            = 1234
	Xstdlib___CHAR_BIT__              = 8
	Xstdlib___DBL_DECIMAL_DIG__       = 17
	Xstdlib___DBL_DIG__               = 15
	Xstdlib___DBL_HAS_DENORM__        = 1
	Xstdlib___DBL_HAS_INFINITY__      = 1
	Xstdlib___DBL_HAS_QUIET_NAN__     = 1
	Xstdlib___DBL_MANT_DIG__          = 53
	Xstdlib___DBL_MAX_10_EXP__        = 308
	Xstdlib___DBL_MAX_EXP__           = 1024
	Xstdlib___DBL_MIN_10_EXP__        = -307
	Xstdlib___DBL_MIN_EXP__           = -1021
	Xstdlib___DEC128_MANT_DIG__       = 34
	Xstdlib___DEC128_MAX_EXP__        = 6145
	Xstdlib___DEC128_MIN_EXP__        = -6142
	Xstdlib___DEC32_MANT_DIG__        = 7
	Xstdlib___DEC32_MAX_EXP__         = 97
	Xstdlib___DEC32_MIN_EXP__         = -94
	Xstdlib___DEC64_MANT_DIG__        = 16
	Xstdlib___DEC64_MAX_EXP__         = 385
	Xstdlib___DEC64_MIN_EXP__         = -382
	Xstdlib___DECIMAL_BID_FORMAT__    = 1
	Xstdlib___DECIMAL_DIG__           = 21
	Xstdlib___DEC_EVAL_METHOD__       = 2
	Xstdlib___FINITE_MATH_ONLY__      = 0
	Xstdlib___FLOAT_WORD_ORDER__      = 1234
	Xstdlib___FLT_DECIMAL_DIG__       = 9
	Xstdlib___FLT_DENORM_MIN__        = 1e-45
	Xstdlib___FLT_DIG__               = 6
	Xstdlib___FLT_EPSILON__           = 1.1920929e-07
	Xstdlib___FLT_EVAL_METHOD__       = 2
	Xstdlib___FLT_HAS_DENORM__        = 1
	Xstdlib___FLT_HAS_INFINITY__      = 1
	Xstdlib___FLT_HAS_QUIET_NAN__     = 1
	Xstdlib___FLT_MANT_DIG__          = 24
	Xstdlib___FLT_MAX_10_EXP__        = 38
	Xstdlib___FLT_MAX_EXP__           = 128
	Xstdlib___FLT_MAX__               = 3.4028235e+38
	Xstdlib___FLT_MIN_10_EXP__        = -37
	Xstdlib___FLT_MIN_EXP__           = -125
	Xstdlib___FLT_MIN__               = 1.1754944e-38
	Xstdlib___FLT_RADIX__             = 2
	Xstdlib___FUNCTION__              = 0
	Xstdlib___GXX_ABI_VERSION         = 1010
	Xstdlib___INT16_MAX__             = 32767
	Xstdlib___INT32_MAX__             = 2147483647
	Xstdlib___INT32_TYPE__            = 0
	Xstdlib___INT64_MAX__             = 9223372036854775807
	Xstdlib___INT8_MAX__              = 127
	Xstdlib___INTMAX_MAX__            = 9223372036854775807
	Xstdlib___INTPTR_MAX__            = 2147483647
	Xstdlib___INTPTR_TYPE__           = 0
	Xstdlib___INT_FAST16_MAX__        = 2147483647
	Xstdlib___INT_FAST16_TYPE__       = 0
	Xstdlib___INT_FAST32_MAX__        = 2147483647
	Xstdlib___INT_FAST32_TYPE__       = 0
	Xstdlib___INT_FAST64_MAX__        = 9223372036854775807
	Xstdlib___INT_FAST8_MAX__         = 127
	Xstdlib___INT_LEAST16_MAX__       = 32767
	Xstdlib___INT_LEAST32_MAX__       = 2147483647
	Xstdlib___INT_LEAST32_TYPE__      = 0
	Xstdlib___INT_LEAST64_MAX__       = 9223372036854775807
	Xstdlib___INT_LEAST8_MAX__        = 127
	Xstdlib___INT_MAX__               = 2147483647
	Xstdlib___LDBL_DENORM_MIN__       = 0
	Xstdlib___LDBL_DIG__              = 18
	Xstdlib___LDBL_EPSILON__          = 1.0842021724855044e-19
	Xstdlib___LDBL_HAS_DENORM__       = 1
	Xstdlib___LDBL_HAS_INFINITY__     = 1
	Xstdlib___LDBL_HAS_QUIET_NAN__    = 1
	Xstdlib___LDBL_MANT_DIG__         = 64
	Xstdlib___LDBL_MAX_10_EXP__       = 4932
	Xstdlib___LDBL_MAX_EXP__          = 16384
	Xstdlib___LDBL_MAX__              = 0
	Xstdlib___LDBL_MIN_10_EXP__       = -4931
	Xstdlib___LDBL_MIN_EXP__          = -16381
	Xstdlib___LDBL_MIN__              = 0
	Xstdlib___LONG_LONG_MAX__         = 9223372036854775807
	Xstdlib___LONG_MAX__              = 2147483647
	Xstdlib___NO_INLINE__             = 1
	Xstdlib___ORDER_BIG_ENDIAN__      = 4321
	Xstdlib___ORDER_LITTLE_ENDIAN__   = 1234
	Xstdlib___ORDER_PDP_ENDIAN__      = 3412
	Xstdlib___PRAGMA_REDEFINE_EXTNAME = 1
	Xstdlib___PTRDIFF_MAX__           = 2147483647
	Xstdlib___PTRDIFF_TYPE__          = 0
	Xstdlib___REGISTER_PREFIX__       = true
	Xstdlib___SCHAR_MAX__             = 127
	Xstdlib___SEG_FS                  = 1
	Xstdlib___SEG_GS                  = 1
	Xstdlib___SHRT_MAX__              = 32767
	Xstdlib___SIG_ATOMIC_MAX__        = 2147483647
	Xstdlib___SIG_ATOMIC_MIN__        = -2147483648
	Xstdlib___SIG_ATOMIC_TYPE__       = 0
	Xstdlib___SIZEOF_DOUBLE__         = 8
	Xstdlib___SIZEOF_FLOAT128__       = 16
	Xstdlib___SIZEOF_FLOAT80__        = 12
	Xstdlib___SIZEOF_FLOAT__          = 4
	Xstdlib___SIZEOF_INT__            = 4
	Xstdlib___SIZEOF_LONG_DOUBLE__    = 12
	Xstdlib___SIZEOF_LONG_LONG__      = 8
	Xstdlib___SIZEOF_LONG__           = 4
	Xstdlib___SIZEOF_POINTER__        = 4
	Xstdlib___SIZEOF_PTRDIFF_T__      = 4
	Xstdlib___SIZEOF_SHORT__          = 2
	Xstdlib___SIZEOF_SIZE_T__         = 4
	Xstdlib___SIZEOF_WCHAR_T__        = 4
	Xstdlib___SIZEOF_WINT_T__         = 4
	Xstdlib___SIZE_MAX__              = 4294967295
	Xstdlib___SSP_STRONG__            = 3
	Xstdlib___STDC_HOSTED__           = 1
	Xstdlib___STDC_IEC_559_COMPLEX__  = 1
	Xstdlib___STDC_IEC_559__          = 1
	Xstdlib___STDC_ISO_10646__        = 201505
	Xstdlib___STDC_NO_THREADS__       = 1
	Xstdlib___STDC_VERSION__          = 199901
	Xstdlib___STDC__                  = 1
	Xstdlib___STRICT_ANSI__           = 1
	Xstdlib___UINT16_MAX__            = 65535
	Xstdlib___UINT32_MAX__            = 4294967295
	Xstdlib___UINT64_MAX__            = 18446744073709551615
	Xstdlib___UINT8_MAX__             = 255
	Xstdlib___UINTMAX_MAX__           = 18446744073709551615
	Xstdlib___UINTPTR_MAX__           = 4294967295
	Xstdlib___UINT_FAST16_MAX__       = 4294967295
	Xstdlib___UINT_FAST32_MAX__       = 4294967295
	Xstdlib___UINT_FAST64_MAX__       = 18446744073709551615
	Xstdlib___UINT_FAST8_MAX__        = 255
	Xstdlib___UINT_LEAST16_MAX__      = 65535
	Xstdlib___UINT_LEAST32_MAX__      = 4294967295
	Xstdlib___UINT_LEAST64_MAX__      = 18446744073709551615
	Xstdlib___UINT_LEAST8_MAX__       = 255
	Xstdlib___USER_LABEL_PREFIX__     = true
	Xstdlib___VERSION__               = 39547
	Xstdlib___WCHAR_MAX__             = 2147483647
	Xstdlib___WCHAR_MIN__             = -2147483648
	Xstdlib___WINT_MAX__              = 4294967295
	Xstdlib___WINT_MIN__              = 0
	Xstdlib___arch__                  = 386
	Xstdlib___code_model_32__         = 1
	Xstdlib___complex__               = 0
	Xstdlib___const                   = 0
	Xstdlib___extension__             = true
	Xstdlib___i386                    = 1
	Xstdlib___i386__                  = 1
	Xstdlib___i686                    = 1
	Xstdlib___i686__                  = 1
	Xstdlib___inline                  = 0
	Xstdlib___ldiv_t_defined          = 1
	Xstdlib___linux                   = 1
	Xstdlib___linux__                 = 1
	Xstdlib___lldiv_t_defined         = 1
	Xstdlib___os__                    = 0
	Xstdlib___pentiumpro              = 1
	Xstdlib___pentiumpro__            = 1
	Xstdlib___restrict                = 0
	Xstdlib___unix                    = 1
	Xstdlib___unix__                  = 1
	Xstdlib___volatile                = 0
)
