// Code generated by running "go generate". DO NOT EDIT.

package Xfuncproto

const (
	XFUNCPROTO              = 15
	XNeedFunctionPrototypes = 1
	XNeedNestedPrototypes   = 1
	XNeedVarargsPrototypes  = 1
	XNeedWidePrototypes     = 0
	X_X_INLINE              = 0
	X_X_RESTRICT_KYWD       = 0
	X_Xconst                = 0
)
