// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/inttypes.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1997-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package inttypes

const (
	XINT16_MAX            = 32767
	XINT16_MIN            = -32768
	XINT32_MAX            = 2147483647
	XINT32_MIN            = 2147483648
	XINT64_MAX            = 9223372036854775807
	XINT64_MIN            = -9223372036854775808
	XINT8_MAX             = 127
	XINT8_MIN             = -128
	XINTMAX_MAX           = 9223372036854775807
	XINTMAX_MIN           = -9223372036854775808
	XINTPTR_MAX           = 9223372036854775807
	XINTPTR_MIN           = -9223372036854775808
	XINT_FAST16_MAX       = 9223372036854775807
	XINT_FAST16_MIN       = -9223372036854775808
	XINT_FAST32_MAX       = 9223372036854775807
	XINT_FAST32_MIN       = -9223372036854775808
	XINT_FAST64_MAX       = 9223372036854775807
	XINT_FAST64_MIN       = -9223372036854775808
	XINT_FAST8_MAX        = 127
	XINT_FAST8_MIN        = -128
	XINT_LEAST16_MAX      = 32767
	XINT_LEAST16_MIN      = -32768
	XINT_LEAST32_MAX      = 2147483647
	XINT_LEAST32_MIN      = 2147483648
	XINT_LEAST64_MAX      = 9223372036854775807
	XINT_LEAST64_MIN      = -9223372036854775808
	XINT_LEAST8_MAX       = 127
	XINT_LEAST8_MIN       = -128
	XPRIX16               = "X"
	XPRIX32               = "X"
	XPRIX8                = "X"
	XPRIXFAST8            = "X"
	XPRIXLEAST16          = "X"
	XPRIXLEAST32          = "X"
	XPRIXLEAST8           = "X"
	XPRId16               = "d"
	XPRId32               = "d"
	XPRId8                = "d"
	XPRIdFAST8            = "d"
	XPRIdLEAST16          = "d"
	XPRIdLEAST32          = "d"
	XPRIdLEAST8           = "d"
	XPRIi16               = "i"
	XPRIi32               = "i"
	XPRIi8                = "i"
	XPRIiFAST8            = "i"
	XPRIiLEAST16          = "i"
	XPRIiLEAST32          = "i"
	XPRIiLEAST8           = "i"
	XPRIo16               = "o"
	XPRIo32               = "o"
	XPRIo8                = "o"
	XPRIoFAST8            = "o"
	XPRIoLEAST16          = "o"
	XPRIoLEAST32          = "o"
	XPRIoLEAST8           = "o"
	XPRIu16               = "u"
	XPRIu32               = "u"
	XPRIu8                = "u"
	XPRIuFAST8            = "u"
	XPRIuLEAST16          = "u"
	XPRIuLEAST32          = "u"
	XPRIuLEAST8           = "u"
	XPRIx16               = "x"
	XPRIx32               = "x"
	XPRIx8                = "x"
	XPRIxFAST8            = "x"
	XPRIxLEAST16          = "x"
	XPRIxLEAST32          = "x"
	XPRIxLEAST8           = "x"
	XPTRDIFF_MAX          = 9223372036854775807
	XPTRDIFF_MIN          = -9223372036854775808
	XSCNd16               = "hd"
	XSCNd32               = "d"
	XSCNd8                = "hhd"
	XSCNdFAST8            = "hhd"
	XSCNdLEAST16          = "hd"
	XSCNdLEAST32          = "d"
	XSCNdLEAST8           = "hhd"
	XSCNi16               = "hi"
	XSCNi32               = "i"
	XSCNi8                = "hhi"
	XSCNiFAST8            = "hhi"
	XSCNiLEAST16          = "hi"
	XSCNiLEAST32          = "i"
	XSCNiLEAST8           = "hhi"
	XSCNo16               = "ho"
	XSCNo32               = "o"
	XSCNo8                = "hho"
	XSCNoFAST8            = "hho"
	XSCNoLEAST16          = "ho"
	XSCNoLEAST32          = "o"
	XSCNoLEAST8           = "hho"
	XSCNu16               = "hu"
	XSCNu32               = "u"
	XSCNu8                = "hhu"
	XSCNuFAST8            = "hhu"
	XSCNuLEAST16          = "hu"
	XSCNuLEAST32          = "u"
	XSCNuLEAST8           = "hhu"
	XSCNx16               = "hx"
	XSCNx32               = "x"
	XSCNx8                = "hhx"
	XSCNxFAST8            = "hhx"
	XSCNxLEAST16          = "hx"
	XSCNxLEAST32          = "x"
	XSCNxLEAST8           = "hhx"
	XSIG_ATOMIC_MAX       = 2147483647
	XSIG_ATOMIC_MIN       = 2147483648
	XSIZE_MAX             = 18446744073709551615
	XUINT16_MAX           = 65535
	XUINT32_MAX           = 4294967295
	XUINT64_MAX           = 18446744073709551615
	XUINT8_MAX            = 255
	XUINTMAX_MAX          = 18446744073709551615
	XUINTPTR_MAX          = 18446744073709551615
	XUINT_FAST16_MAX      = 18446744073709551615
	XUINT_FAST32_MAX      = 18446744073709551615
	XUINT_FAST64_MAX      = 18446744073709551615
	XUINT_FAST8_MAX       = 255
	XUINT_LEAST16_MAX     = 65535
	XUINT_LEAST32_MAX     = 4294967295
	XUINT_LEAST64_MAX     = 18446744073709551615
	XUINT_LEAST8_MAX      = 255
	XWCHAR_MAX            = 0
	XWCHAR_MIN            = 0
	XWINT_MAX             = 4294967295
	XWINT_MIN             = 0
	X_INTTYPES_H          = 1
	X_STDINT_H            = 1
	X__PRI64_PREFIX       = "l"
	X__PRIPTR_PREFIX      = "l"
	X____gwchar_t_defined = 1
)
