// Code generated by running "go generate". DO NOT EDIT.

package dlfcn

const (
	XRTLD_BINDING_MASK = 3
	XRTLD_DEEPBIND     = 8
	XRTLD_GLOBAL       = 256
	XRTLD_LAZY         = 1
	XRTLD_LOCAL        = 0
	XRTLD_NODELETE     = 4096
	XRTLD_NOLOAD       = 4
	XRTLD_NOW          = 2
	X_DLFCN_H          = 1
)
