// Code generated by running "go generate". DO NOT EDIT.


// ----------------------------------------------------------------------------
//      /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */


package libc

const (
Mman_MAP_FIXED = 16
Mman_MAP_PRIVATE = 2
Mman_MAP_SHARED = 1
Mman_MCL_CURRENT = 1
Mman_MCL_FUTURE = 2
Mman_MCL_ONFAULT = 4
Mman_MS_ASYNC = 1
Mman_MS_INVALIDATE = 2
Mman_MS_SYNC = 4
Mman_PROT_EXEC = 4
Mman_PROT_GROWSDOWN = 16777216
Mman_PROT_GROWSUP = 33554432
Mman_PROT_NONE = 0
Mman_PROT_READ = 1
Mman_PROT_WRITE = 2
Mman__BITS_TYPES_H = 1
Mman__SYS_MMAN_H = 1
Mman___S32_TYPE = 0
Mman___SLONG32_TYPE = 0
Mman_mmap = 0
)
