// Code generated by running "go generate". DO NOT EDIT.



package sched

const (
X_BITS_TYPES_H = 1
X_SCHED_H = 1
X__S32_TYPE = 0
X__S64_TYPE = 0
X__SQUAD_TYPE = 0
X__SWORD_TYPE = 0
X__U64_TYPE = 0
X__UQUAD_TYPE = 0
Xsched_priority = 0
)
