// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/signal.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/bits/pthreadtypes.h
// ----------------------------------------------------------------------------
/* Copyright (C) 2002-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

// ----------------------------------------------------------------------------
//      /usr/include/sys/wait.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package wait

const (
	X_BITS_PTHREADTYPES_H              = 1
	X_BITS_TYPES_H                     = 1
	X_EXTERN_INLINE                    = 0
	X_SIGSET_H_fns                     = 1
	X_SIGSET_H_types                   = 1
	X_SYS_WAIT_H                       = 1
	X__PTHREAD_MUTEX_HAVE_PREV         = 1
	X__PTHREAD_RWLOCK_INT_FLAGS_SHARED = 1
	X__S32_TYPE                        = 0
	X__SIGEV_MAX_SIZE                  = 64
	X__SIZEOF_PTHREAD_ATTR_T           = 56
	X__SIZEOF_PTHREAD_BARRIERATTR_T    = 4
	X__SIZEOF_PTHREAD_BARRIER_T        = 32
	X__SIZEOF_PTHREAD_CONDATTR_T       = 4
	X__SIZEOF_PTHREAD_COND_T           = 48
	X__SIZEOF_PTHREAD_MUTEXATTR_T      = 4
	X__SIZEOF_PTHREAD_MUTEX_T          = 40
	X__SIZEOF_PTHREAD_RWLOCKATTR_T     = 8
	X__SIZEOF_PTHREAD_RWLOCK_T         = 56
	X__SI_MAX_SIZE                     = 128
	X__SLONG32_TYPE                    = 0
	X__have_pthread_attr_t             = 1
	X__have_sigevent_t                 = 1
	X__have_siginfo_t                  = 1
	X__have_sigval_t                   = 1
	Xsignal                            = 0
	XBUS_ADRALN                        = 1
	XBUS_ADRERR                        = 2
	XBUS_MCEERR_AO                     = 5
	XBUS_MCEERR_AR                     = 4
	XBUS_OBJERR                        = 3
	XCLD_CONTINUED                     = 6
	XCLD_DUMPED                        = 3
	XCLD_EXITED                        = 1
	XCLD_KILLED                        = 2
	XCLD_STOPPED                       = 5
	XCLD_TRAPPED                       = 4
	XFPE_FLTDIV                        = 3
	XFPE_FLTINV                        = 7
	XFPE_FLTOVF                        = 4
	XFPE_FLTRES                        = 6
	XFPE_FLTSUB                        = 8
	XFPE_FLTUND                        = 5
	XFPE_INTDIV                        = 1
	XFPE_INTOVF                        = 2
	XILL_BADSTK                        = 8
	XILL_COPROC                        = 7
	XILL_ILLADR                        = 3
	XILL_ILLOPC                        = 1
	XILL_ILLOPN                        = 2
	XILL_ILLTRP                        = 4
	XILL_PRVOPC                        = 5
	XILL_PRVREG                        = 6
	XPOLL_ERR                          = 4
	XPOLL_HUP                          = 6
	XPOLL_IN                           = 1
	XPOLL_MSG                          = 3
	XPOLL_OUT                          = 2
	XPOLL_PRI                          = 5
	XP_ALL                             = 0
	XP_PGID                            = 2
	XP_PID                             = 1
	XSEGV_ACCERR                       = 2
	XSEGV_MAPERR                       = 1
	XSIGEV_NONE                        = 1
	XSIGEV_SIGNAL                      = 0
	XSIGEV_THREAD                      = 2
	XSIGEV_THREAD_ID                   = 4
	XSI_ASYNCIO                        = -4
	XSI_ASYNCNL                        = -60
	XSI_KERNEL                         = 128
	XSI_MESGQ                          = -3
	XSI_QUEUE                          = -1
	XSI_SIGIO                          = -5
	XSI_TIMER                          = -2
	XSI_TKILL                          = -6
	XSI_USER                           = 0
	XTRAP_BRKPT                        = 1
	XTRAP_TRACE                        = 2
)
