// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/lib/gcc/i686-linux-gnu/6/include/stddef.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1989-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */

package mman

const (
	XMAP_FIXED      = 16
	XMAP_PRIVATE    = 2
	XMAP_SHARED     = 1
	XMCL_CURRENT    = 1
	XMCL_FUTURE     = 2
	XMCL_ONFAULT    = 4
	XMS_ASYNC       = 1
	XMS_INVALIDATE  = 2
	XMS_SYNC        = 4
	XPROT_EXEC      = 4
	XPROT_GROWSDOWN = 16777216
	XPROT_GROWSUP   = 33554432
	XPROT_NONE      = 0
	XPROT_READ      = 1
	XPROT_WRITE     = 2
	X_BITS_TYPES_H  = 1
	X_SYS_MMAN_H    = 1
	X__S32_TYPE     = 0
	X__S64_TYPE     = 0
	X__SQUAD_TYPE   = 0
	X__SWORD_TYPE   = 0
	X__U64_TYPE     = 0
	X__UQUAD_TYPE   = 0
	Xmmap           = 0
)
