// Code generated by running "go generate". DO NOT EDIT.



package fcntl

const (
XF_OK = 0
XO_ACCMODE = 3
XO_APPEND = 8
XO_BINARY = 32768
XO_CREAT = 256
XO_EXCL = 1024
XO_NOINHERIT = 128
XO_RANDOM = 16
XO_RAW = 32768
XO_RDONLY = 0
XO_RDWR = 2
XO_SEQUENTIAL = 32
XO_TEMPORARY = 64
XO_TEXT = 16384
XO_TRUNC = 512
XO_WRONLY = 1
XR_OK = 4
XW_OK = 2
XX_OK = 1
X_A_ARCH = 32
X_A_HIDDEN = 2
X_A_NORMAL = 0
X_A_RDONLY = 1
X_A_SUBDIR = 16
X_A_SYSTEM = 4
X_CRT_PACKING = 8
X_MSC_VER = 1200
X_O_ACCMODE = 3
X_O_APPEND = 8
X_O_BINARY = 32768
X_O_CREAT = 256
X_O_EXCL = 1024
X_O_NOINHERIT = 128
X_O_RANDOM = 16
X_O_RAW = 32768
X_O_RDONLY = 0
X_O_RDWR = 2
X_O_SEQUENTIAL = 32
X_O_SHORT_LIVED = 4096
X_O_TEMPORARY = 64
X_O_TEXT = 16384
X_O_TRUNC = 512
X_O_U16TEXT = 131072
X_O_U8TEXT = 262144
X_O_WRONLY = 1
X_O_WTEXT = 65536
X__USE_MINGW_ANSI_STDIO = 0
X__forceinline = 0
X__inline = 0
X__int32 = 0
X_finddata_t = 0
X_finddatai64_t = 0
X_findfirst = 0
X_findfirsti64 = 0
X_findnext = 0
X_findnexti64 = 0
X_wfinddata_t = 0
X_wfinddatai64_t = 0
X_wfindfirst = 0
X_wfindfirsti64 = 0
X_wfindnext = 0
X_wfindnexti64 = 0
Xlseek = 0
)
