// Code generated by running "go generate". DO NOT EDIT.

// +build ignore

// source: /usr/lib/gcc/i686-linux-gnu/6/include/stdarg.h

#define _STDARG_H
#define _ANSI_STDARG_H_
#define __GNUC_VA_LIST
typedef __builtin_va_list __gnuc_va_list;
#define va_start(v, l) __builtin_va_start ( v , l )
#define va_end(v) __builtin_va_end ( v )
#define va_arg(v, l) __builtin_va_arg ( v , l )
#define va_copy(d, s) __builtin_va_copy ( d , s )
#define __va_copy(d, s) __builtin_va_copy ( d , s )
typedef __gnuc_va_list va_list;
#define _VA_LIST_
#define _VA_LIST
#define _VA_LIST_DEFINED
#define _VA_LIST_T_H
#define __va_list__
