// Code generated by running "go generate". DO NOT EDIT.

// +build ignore

// source: /usr/include/stdio.h

#define _STDIO_H 1
struct _IO_FILE;
typedef struct _IO_FILE FILE;
#define __FILE_defined 1
typedef struct _IO_FILE __FILE;
#define ____FILE_defined 1
#define _STDIO_USES_IOSTREAM
typedef _G_fpos_t fpos_t;
#define _IOFBF 0
#define _IOLBF 1
#define _IONBF 2
#define BUFSIZ _IO_BUFSIZ
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
extern struct _IO_FILE *stdin;
extern struct _IO_FILE *stdout;
extern struct _IO_FILE *stderr;
#define stdin stdin
#define stdout stdout
#define stderr stderr
extern int remove(char *__filename);
extern int rename(char *__old, char *__new);
extern FILE *tmpfile(void);
extern char *tmpnam(char *__s);
extern int fclose(FILE * __stream);
extern int fflush(FILE * __stream);
extern FILE *fopen(char *__filename, char *__modes);
extern FILE *freopen(char *__filename, char *__modes, FILE * __stream);
extern void setbuf(FILE * __stream, char *__buf);
extern int setvbuf(FILE * __stream, char *__buf, int __modes, size_t __n);
extern int fprintf(FILE * __stream, char *__format, ...);
extern int printf(char *__format, ...);
extern int sprintf(char *__s, char *__format, ...);
extern int vfprintf(FILE * __s, char *__format, __gnuc_va_list __arg);
extern int vprintf(char *__format, __gnuc_va_list __arg);
extern int vsprintf(char *__s, char *__format, __gnuc_va_list __arg);
extern int snprintf(char *__s, size_t __maxlen, char *__format, ...);
extern int vsnprintf(char *__s, size_t __maxlen, char *__format, __gnuc_va_list __arg);
extern int fscanf(FILE * __stream, char *__format, ...);
extern int scanf(char *__format, ...);
extern int sscanf(char *__s, char *__format, ...);
extern int __isoc99_fscanf(FILE * __stream, char *__format, ...);
extern int __isoc99_scanf(char *__format, ...);
extern int __isoc99_sscanf(char *__s, char *__format, ...);
#define fscanf __isoc99_fscanf
#define scanf __isoc99_scanf
#define sscanf __isoc99_sscanf
extern int vfscanf(FILE * __s, char *__format, __gnuc_va_list __arg);
extern int vscanf(char *__format, __gnuc_va_list __arg);
extern int vsscanf(char *__s, char *__format, __gnuc_va_list __arg);
extern int __isoc99_vfscanf(FILE * __s, char *__format, __gnuc_va_list __arg);
extern int __isoc99_vscanf(char *__format, __gnuc_va_list __arg);
extern int __isoc99_vsscanf(char *__s, char *__format, __gnuc_va_list __arg);
#define vfscanf __isoc99_vfscanf
#define vscanf __isoc99_vscanf
#define vsscanf __isoc99_vsscanf
extern int fgetc(FILE * __stream);
extern int getc(FILE * __stream);
extern int getchar(void);
#define getc(_fp) _IO_getc ( _fp )
extern int fputc(int __c, FILE * __stream);
extern int putc(int __c, FILE * __stream);
extern int putchar(int __c);
#define putc(_ch, _fp) _IO_putc ( _ch , _fp )
extern char *fgets(char *__s, int __n, FILE * __stream);
extern char *gets(char *__s);
extern int fputs(char *__s, FILE * __stream);
extern int puts(char *__s);
extern int ungetc(int __c, FILE * __stream);
extern size_t fread(void *__ptr, size_t __size, size_t __n, FILE * __stream);
extern size_t fwrite(void *__ptr, size_t __size, size_t __n, FILE * __s);
extern int fseek(FILE * __stream, long int __off, int __whence);
extern long int ftell(FILE * __stream);
extern void rewind(FILE * __stream);
extern int fgetpos(FILE * __stream, fpos_t * __pos);
extern int fsetpos(FILE * __stream, fpos_t * __pos);
extern void clearerr(FILE * __stream);
extern int feof(FILE * __stream);
extern int ferror(FILE * __stream);
extern void perror(char *__s);
