// Code generated by running "go generate". DO NOT EDIT.

// ----------------------------------------------------------------------------
//      /usr/include/sys/resource.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1992-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

package resource

const (
	XPRIO_MAX            = 20
	XPRIO_MIN            = -20
	XRLIM64_INFINITY     = 18446744073709551615
	XRLIMIT_LOCKS        = 0
	XRLIMIT_MEMLOCK      = 0
	XRLIMIT_MSGQUEUE     = 0
	XRLIMIT_NICE         = 0
	XRLIMIT_NLIMITS      = 0
	XRLIMIT_NPROC        = 0
	XRLIMIT_OFILE        = 0
	XRLIMIT_RSS          = 0
	XRLIMIT_RTPRIO       = 0
	XRLIMIT_RTTIME       = 0
	XRLIMIT_SIGPENDING   = 0
	XRLIM_INFINITY       = 18446744073709551615
	XRLIM_NLIMITS        = 0
	XRLIM_SAVED_CUR      = 18446744073709551615
	XRLIM_SAVED_MAX      = 18446744073709551615
	X_BITS_TYPES_H       = 1
	X_STRUCT_TIMEVAL     = 1
	X_SYS_RESOURCE_H     = 1
	X__S32_TYPE          = 0
	X__SLONG32_TYPE      = 0
	Xgetrlimit           = 0
	Xsetrlimit           = 0
	XPRIO_PGRP           = 1
	XPRIO_PROCESS        = 0
	XPRIO_USER           = 2
	XRLIMIT_AS           = 9
	XRLIMIT_CORE         = 4
	XRLIMIT_CPU          = 0
	XRLIMIT_DATA         = 2
	XRLIMIT_FSIZE        = 1
	XRLIMIT_NOFILE       = 7
	XRLIMIT_STACK        = 3
	XRUSAGE_CHILDREN     = -1
	XRUSAGE_SELF         = 0
	X__RLIMIT_LOCKS      = 10
	X__RLIMIT_MEMLOCK    = 8
	X__RLIMIT_MSGQUEUE   = 12
	X__RLIMIT_NICE       = 13
	X__RLIMIT_NLIMITS    = 16
	X__RLIMIT_NPROC      = 6
	X__RLIMIT_OFILE      = 7
	X__RLIMIT_RSS        = 5
	X__RLIMIT_RTPRIO     = 14
	X__RLIMIT_RTTIME     = 15
	X__RLIMIT_SIGPENDING = 11
	X__RLIM_NLIMITS      = 16
)
