// Code generated by running "go generate". DO NOT EDIT.


// ----------------------------------------------------------------------------
//      m:\mingw\lib\gcc\x86_64-w64-mingw32\6.3.0\include\stdbool.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1998-2016 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Under Section 7 of GPL version 3, you are granted additional
permissions described in the GCC Runtime Library Exception, version
3.1, as published by the Free Software Foundation.

You should have received a copy of the GNU General Public License and
a copy of the GCC Runtime Library Exception along with this program;
see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
<http://www.gnu.org/licenses/>.  */


package stdbool

const (
X_MSC_VER = 1200
X__USE_MINGW_ANSI_STDIO = 0
X__bool_true_false_are_defined = 1
X__forceinline = 0
X__inline = 0
X__int32 = 0
Xbool = 0
Xfalse = 0
Xtrue = 1
)
