// Code generated by running "go generate". DO NOT EDIT.

// +build ignore

// ----------------------------------------------------------------------------
//      /usr/include/i386-linux-gnu/sys/wait.h
// ----------------------------------------------------------------------------
/* Copyright (C) 1991-2016 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

#define _SYS_WAIT_H (1)
#define WEXITSTATUS(status) __WEXITSTATUS ( status )
#define WTERMSIG(status) __WTERMSIG ( status )
#define WSTOPSIG(status) __WSTOPSIG ( status )
#define WIFEXITED(status) __WIFEXITED ( status )
#define WIFSIGNALED(status) __WIFSIGNALED ( status )
#define WIFSTOPPED(status) __WIFSTOPPED ( status )
#define WIFCONTINUED(status) __WIFCONTINUED ( status )
extern __pid_t wait(int *__stat_loc);
extern __pid_t waitpid(__pid_t __pid, int *__stat_loc, int __options);
#define WNOHANG (1)
#define WUNTRACED (2)
#define WSTOPPED (2)
#define WEXITED (4)
#define WCONTINUED (8)
#define WNOWAIT (16777216)
#define __WNOTHREAD (536870912)
#define __WALL (1073741824)
#define __WCLONE (2147483648u)
