// Code generated by running "go generate". DO NOT EDIT.

// +build ignore

// source: /usr/include/x86_64-linux-gnu/sys/wait.h

#define _SYS_WAIT_H 1
#define WEXITSTATUS(status) __WEXITSTATUS ( status )
#define WTERMSIG(status) __WTERMSIG ( status )
#define WSTOPSIG(status) __WSTOPSIG ( status )
#define WIFEXITED(status) __WIFEXITED ( status )
#define WIFSIGNALED(status) __WIFSIGNALED ( status )
#define WIFSTOPPED(status) __WIFSTOPPED ( status )
#define WIFCONTINUED(status) __WIFCONTINUED ( status )
extern __pid_t wait(int *__stat_loc);
extern __pid_t waitpid(__pid_t __pid, int *__stat_loc, int __options);
