// Code generated by running "go generate". DO NOT EDIT.

package select_

const (
	XFD_SETSIZE              = 1024
	X_BITS_TYPESIZES_H       = 1
	X_BITS_TYPES_H           = 1
	X_SIGSET_H_types         = 1
	X_STRUCT_TIMEVAL         = 1
	X_SYS_SELECT_H           = 1
	X__CLOCKID_T_TYPE        = 0
	X__DADDR_T_TYPE          = 0
	X__FD_SETSIZE            = 1024
	X__INO_T_MATCHES_INO64_T = 1
	X__KEY_T_TYPE            = 0
	X__OFF_T_MATCHES_OFF64_T = 1
	X__PID_T_TYPE            = 0
	X__S32_TYPE              = 0
	X__SLONG32_TYPE          = 0
)
